#!/bin/bash
# Written by Sean Donovan (swordrune10)
cd $REPOS/$SCRIPT_REPO-ics/out/target/product/$SCRIPT_DEVICE/system  &> /dev/null

if ( find build.prop &> /dev/null );then
	rm build.prop
fi
cd ..
if ( find *.zip &> /dev/null );then
	rm *.zip*
fi

processors=$( cat /proc/cpuinfo | grep "physical id" | sort -u | wc -l )
cores=$( cat /proc/cpuinfo | grep -m 1 "cpu cores" | grep -o [0-9] )
threads=$( cat /proc/cpuinfo | grep -m 1 siblings | grep -o [0-9] )

THREADS_TOTAL=$( expr $processors \* $threads \* $cores )

cd $REPOS/$SCRIPT_REPO-ics
. build/envsetup.sh

if [ $SCRIPT_REPO == "cm" ] || [ $SCRIPT_REPO == "sts" ]; then
	brunch $SCRIPT_DEVICE -j$THREADS_TOTAL
	exit 0
fi

if [ $SCRIPT_REPO == "aokp" ]; then
	vendor_lunch=$(echo "aokp_")
fi

if [ $SCRIPT_REPO == "evervolv" ]; then
	vendor_lunch=$(echo "ev_")
fi

if [ $SCRIPT_REPO == "gummy" ]; then
	vendor_lunch=$(echo "Gummy_")
fi

if [ $SCRIPT_REPO == "aosp" ] || [ $SCRIPT_REPO == "rooted-aosp" ]; then
	vendor_lunch=$(echo "full_")
fi

if [ ! $SCRIPT_REPO == "cm" ] || [ ! $SCRIPT_REPO == "sts" ]; then
	lunch $vendor_lunch$SCRIPT_DEVICE-userdebug
	make CC=gcc-4.4 CXX=g++-4.4 otapackage -j$THREADS_TOTAL
	exit 0
fi

echo "This is awkward... how did u get here??"
read bullshitanswer
