#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear
export REPOS=$(echo "$LOCAL/../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Which version of android are we building today?"
echo "  1. Cyanogenmod"
echo "  2. AOSP"
echo "  3. Go Back"
read version

if [ $version == "1" ]; then
	export SCRIPT_REPO=$(echo "cm")
fi

if [ $version == "2" ]; then
	export SCRIPT_REPO=$(echo "aosp")
fi

clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Please type in which device you would like to build"
echo "Type in list to see all supported devices"
echo "Type in exit to go to main menu"
read device

if [ $device == "list" ]; then
	if [ $SCRIPT_REPO == "cm" ]; then
		sed -e 's/.*cm_//g' \
		-e 's/-userdebug//' \
		$REPOS/cm-ics/vendor/cm/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "aosp" ]; then
		echo "stingray
		wingray
		crespo4g
		crespo
		maguro
		toro
		tuna" | less
	fi

	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Please type in which device you would like to build"
	echo "Type in exit to go to main menu"
	read device
fi

if [ $device == "exit" ]; then
	echo ""
	echo "Press Enter to continue"
	read done
	exit 0
fi

if [ ! $version == "3" ]; then
	clear

	$LOCAL/.scripts/setupandro

	export SCRIPT_DEVICE=$(echo $device)
	$LOCAL/.scripts/buildandro
	$LOCAL/.scripts/setupprop
fi

echo ""
echo "Press Enter to continue"
read done
