#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Which version of android are we building today?"
echo "  1. Cyanogenmod 9"
echo "  2. Rooted & Busyboxed AOSP"
echo "  3. Android Open Kang Project"
echo "  4. Team Gummy"
echo "  5. Android Open Source Project"
echo "  6. Go Back"
read version

if [ $version == "1" ]; then
	export SCRIPT_REPO=$(echo "cm")
fi

if [ $version == "2" ]; then
	export SCRIPT_REPO=$(echo "rooted-aosp")
fi

if [ $version == "3" ]; then
	export SCRIPT_REPO=$(echo "aokp")
fi

if [ $version == "4" ]; then
	export SCRIPT_REPO=$(echo "gummy")
fi

if [ $version == "5" ]; then
	export SCRIPT_REPO=$(echo "aosp")
fi

if [ ! $version == "6" ]; then
	clear

	./setupandro

	export SCRIPT_DEVICE=$(echo "stingray")
	./buildandro
	./setupprop

	export SCRIPT_DEVICE=$(echo "wingray")
	./buildandro
	./setupprop
fi
