#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Which version of android are we building today?"
echo "  1. Cyanogenmod 9"
echo "  2. Rooted & Busyboxed AOSP"
echo "  3. Android Open Kang Project"
echo "  4. Team Gummy"
echo "  5. Android Open Source Project"
echo "  6. Go Back"
read version

if [ "$version" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	kitchenbuilder
	exit 0
fi

if ( echo $version | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	kitchenbuilder
	exit 0
fi

if [ $version -gt "6" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	kitchenbuilder
	exit 0
fi

if [ $version == "1" ]; then
	export SCRIPT_REPO=$(echo "cm")
fi

if [ $version == "2" ]; then
	export SCRIPT_REPO=$(echo "rooted-aosp")
fi

if [ $version == "3" ]; then
	export SCRIPT_REPO=$(echo "aokp")
fi

if [ $version == "4" ]; then
	export SCRIPT_REPO=$(echo "gummy")
fi

if [ $version == "5" ]; then
	export SCRIPT_REPO=$(echo "aosp")
fi

clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Please type in which device you would like to build"
echo "Type in list to see all supported devices"
echo "Type in exit to go back"
read device

if [ "$device" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	kitchenbuilder
	exit 0
fi

while [ $device == "list" ]; do
	if [ $SCRIPT_REPO == "cm" ]; then
		sed -e 's/.*cm_//g' \
		-e 's/-userdebug//' \
		$REPOS/cm-ics/vendor/cm/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "aokp" ]; then
		sed -e 's/.*aokp_//g' \
		-e 's/-userdebug//' \
		$REPOS/aokp-ics/vendor/aokp/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "gummy" ]; then
		sed -e 's/.*Gummy_//g' \
		-e 's/-userdebug//' \
		$REPOS/gummy-ics/vendor/Gummy/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "rooted-aosp" ]; then

echo "stingray
wingray
crespo4g
crespo
maguro
toro
toroplus
tuna" | less

	fi

	if [ $SCRIPT_REPO == "aosp" ]; then

echo "stingray
wingray
crespo4g
crespo
maguro
toro
tuna" | less

	fi

	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Please type in which device you would like to build"
	echo "Type in list to see all supported devices"
	echo "Type in exit to go to back"
	read device
done

if [ "$device" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	kitchenbuilder
	exit 0
fi

if [ $device == "exit" ]; then
	exit 0
fi

if [ $SCRIPT_REPO == "cm" ]; then
	if ( ! sed -e 's/.*cm_//g' \
	-e 's/-userdebug//' \
	$REPOS/cm-ics/vendor/cm/vendorsetup.sh | grep -q $device ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done

		kitchenbuilder
		exit 0
	fi
fi

if [ $SCRIPT_REPO == "aokp" ]; then
	if ( ! sed -e 's/.*aokp_//g' \
	-e 's/-userdebug//' \
	$REPOS/aokp-ics/vendor/aokp/vendorsetup.sh | grep -q $device ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done

		kitchenbuilder
		exit 0
	fi
fi

if [ $SCRIPT_REPO == "gummy" ]; then
	if ( ! sed -e 's/.*Gummy_//g' \
	-e 's/-userdebug//' \
	$REPOS/gummy-ics/vendor/Gummy/vendorsetup.sh | grep -q $device ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done

		kitchenbuilder
		exit 0
	fi
fi

if [ $SCRIPT_REPO == "rooted-aosp" ]; then
	if ( ! echo "stingray
	wingray
	crespo4g
	crespo
	maguro
	toro
	toroplus
	tuna" | grep -q $device ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done

		kitchenbuilder
		exit 0
	fi

fi

if [ $SCRIPT_REPO == "aosp" ]; then
	if ( ! echo "stingray
	wingray
	crespo4g
	crespo
	maguro
	toro
	tuna" | grep -q $device ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done

		kitchenbuilder
		exit 0
	fi
fi

if [ ! $version == "6" ]; then
	clear

	setupandro

	export SCRIPT_DEVICE=$(echo $device)
	buildandro
	setupprop
fi
