#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Which version of android are we building today?"
echo "  1. Cyanogenmod"
echo "  2. Rooted & Busyboxed AOSP"
echo "  3. Pure AOSP"
echo "  4. Go Back"
read version

if [ $version == "1" ]; then
	export SCRIPT_REPO=$(echo "cm")
fi

if [ $version == "2" ]; then
	export SCRIPT_REPO=$(echo "rooted-aosp")
fi

if [ $version == "3" ]; then
	export SCRIPT_REPO=$(echo "aosp")
fi

if [ $version == "4" ]; then
	exit 0
fi

clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Please type in which device you would like to build"
echo "Type in list to see all supported devices"
echo "Type in exit to go back"
read device

if [ $device == "list" ]; then
	if [ $SCRIPT_REPO == "cm" ]; then
		sed -e 's/.*cm_//g' \
		-e 's/-userdebug//' \
		$REPOS/cm-ics/vendor/cm/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "aokp" ]; then
		sed -e 's/.*aokp_//g' \
		-e 's/-userdebug//' \
		$REPOS/cm-ics/vendor/cm/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "gummy" ]; then
		sed -e 's/.*Gummy_//g' \
		-e 's/-userdebug//' \
		$REPOS/cm-ics/vendor/cm/vendorsetup.sh | less
	fi

	if [ $SCRIPT_REPO == "rooted-aosp" ]; then

echo "stingray
wingray
crespo4g
crespo
maguro
toro
toroplus
tuna" | less

	fi

	if [ $SCRIPT_REPO == "aosp" ]; then

echo "stingray
wingray
crespo4g
crespo
maguro
toro
tuna" | less

	fi

	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Please type in which device you would like to build"
	echo "Type in exit to go to back"
	read device
fi

if [ $device == "exit" ]; then
	exit 0
fi

if [ ! $version == "4" ]; then
	clear

	./setupandro

	export SCRIPT_DEVICE=$(echo $device)
	./buildandro
	./setupprop
fi
