#!/bin/sh
if ( find .scripts &> /dev/null ); then
	.scripts/bouncer

	if ( uname -a | grep -q Darwin ); then
		.scripts/macosxinit
	fi
else
	echo "Can not start program, aborting.."
	exit 0
fi

export START=true
./headerfile
