#!/bin/sh
cd $(dirname $( readlink -f $0 ) )
if ( find .scripts 2> /dev/null 1>&2 ); then
	cd .scripts
	./bouncer

	if ( uname -a | grep -q Darwin ); then
		./macosxinit
	fi
else
	clear

	echo "An Error Has Occurred!"
	echo "======================"
	echo "If you see this in error, please notify me at either xda or rootzwiki"
	echo "if you prefer email you can reach me at mishana@swordrune10.net"
	echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
	read -p "Press Enter to exit.." done
	exit 0
fi

export START=true
./headerfile
