#!/bin/bash
# Declare global variables
if ( uname -a | grep -q Darwin ); then
	export POSIXLY_CORRECT=1
	export LOCAL=$( echo "/Volumes/android/swordkitchen/.scripts" )
else
	export LOCAL=$( cd $(dirname $0) && pwd )
fi

if [ $LOCAL == $HOME/bin/kitchen ]; then
	export REPOS=$( echo "$LOCAL/../../Documents/android/repos" )
else
	export REPOS=$( echo "$LOCAL/../../repos" )
fi

export BUILDS=$( echo "$REPOS/../builds" )

if ( find $BUILDS/../publish &> /dev/null); then
	cd $BUILDS/../publish
	export PUBLISH=$( pwd )
fi

# ::::::::::::::::::::::::::::::::::::::::::::::

# Declare paths
if ( ! echo $PATH | grep -q "$HOME/bin:" ); then
	export PATH="$HOME/bin:$PATH"
fi

if ( ! echo $PATH | grep -q $LOCAL ); then
	export PATH="$LOCAL/config:$PATH"
	export PATH="$LOCAL/menu:$PATH"
	export PATH="$LOCAL/update:$PATH"
	export PATH="$LOCAL/build:$PATH"
	export PATH="$LOCAL:$PATH"
fi

if ( find $BUILDS/../publish &> /dev/null) && ( ! echo $PATH | grep -q "$HOME/bin/publish:" ); then
	export PATH="$PUBLISH:$PATH"
fi

# ::::::::::::::::::::::::::::::::::::::::::::::

# Create necessary files/folders
mkdir -p $LOCAL/config
mkdir -p $LOCAL/xml

if ( ! find $LOCAL/config/gitpuller &> /dev/null ); then
	export AUTHOR="gitpuller"
	scriptmakir
	chmod a+x $LOCAL/config/gitpuller
fi

if ( ! find $LOCAL/config/otherrepo &> /dev/null ); then
	touch $LOCAL/config/otherrepo
fi

if ( ! find $LOCAL/config/romeditor &> /dev/null ); then
	export AUTHOR="romeditor"
	scriptmakir
	chmod a+x $LOCAL/config/romeditor
fi

# ::::::::::::::::::::::::::::::::::::::::::::::

# Declare number of threads from processor
processors=$( cat /proc/cpuinfo | grep "physical id" | sort -u | wc -l )
cores=$( cat /proc/cpuinfo | grep -m 1 "cpu cores" | grep -o [0-9] )
threads=$( cat /proc/cpuinfo | grep -m 1 siblings | grep -o [0-9] )

export THREADS_TOTAL=$( expr $processors \* $threads \* $cores )

# ::::::::::::::::::::::::::::::::::::::::::::::

export INIT=true
