#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "kitchen")
	./headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Main Menu:"
echo "  1. Setup Kitchen"
echo "  2. Configure Kitchen"
echo "  3. Update Kitchen"
echo "  4. Run Kitchen"
echo "  5. Fix Kitchen"
echo "  6. Auto Build Kitchen"
echo "  7. Exit"
echo ""
echo "Which one would you like to do?"
read answer

if [ ! "$answer" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if ( echo $answer | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $answer -gt "10" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $answer == "1" ]; then
	reposetup
fi

if [ $answer == "2" ]; then
	configkitchen
fi

if [ $answer == "3" ]; then
	reposync
fi

if [ $answer == "4" ]; then
	buildmenu
fi

if [ $answer == "5" ]; then
	fixkitchen
fi

if [ $answer == "6" ]; then
	buildautomenu
fi

if [ $answer == "7" ]; then
	echo ""
	echo "Thank you for using Swordrune10's Kitchen! Good bye.."
	exit 0
fi

if [ $answer == "8" ] || [ $answer == "9" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $answer == "10" ]; then
	echo ""
	echo "You seem bored.. wanna watch a movie?"
	read nothing
	if [ $nothing == "no" ] || [ $nothing == "n" ]; then
		echo "tough!"
	fi
	telnet towel.blinkenlights.nl
fi
menu
}
menu
