#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Something is not working right? What should we do?"
echo "Clean = remove files, download from origin"
echo "Purge = delete it!"
echo "  1. Clean/Purge a certain repository"
echo "  2. Clean/Purge all the repositories"
echo "  3. Clean/Purge the Kitchen app"
echo "  4. Purge the whole Kitchen!"
echo "  5. Purge all things!!"
echo "  6. Go Back"
echo ""
echo "Which one would you like to do?"
read cleananswer

if [ $cleananswer == "1" ]; then
	echo ""
	echo "which repo would you like to modify?"
	echo "Cyanogenmod 9 = cm"
	echo "Rooted & Busyboxed AOSP = rooted-aosp"
	echo "Android Open Source Project = aosp"
	echo "type exit to go to main menu"
	read modify

	if [ $modify == "exit" ]; then
		exit 0
	fi

	echo ""
	echo "Clean or Purge?"
	echo "Clean = remove files, download from origin"
	echo "Purge = delete it!"
	echo "type exit to go to main menu"
	read remover

	if [ $remover == "exit" ]; then
		exit 0
	fi

	cd $REPOS/$modify-ics

	if [ $remover == "Clean" ] || [ $remover == "clean" ]; then
		rm -rf *
		repo sync
	fi

	if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
		cd ..
		rm -rf $modify-ics
	fi
	
fi

if [ $cleananswer == "2" ]; then
	echo ""
	echo "Clean or Purge the repositories?"
	echo "Clean = remove files, download from origin"
	echo "Purge = delete all!"
	echo "type exit to go to main menu"
	read remover

	if [ $remover == "exit" ]; then
		exit 0
	fi

	if ( find $REPOS/cm-ics &> /dev/null )
		cd $REPOS/cm-ics

		if [ $remover == "Clean" ] || [ $remover == "clean" ]; then
			rm -rf *
			repo sync
		fi

		if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
			cd ..
			rm -rf cm-ics
		fi
	fi

	if ( find $REPOS/rooted-aosp-ics &> /dev/null )
		cd $REPOS/rooted-aosp-ics

		if [ $remover == "Clean" ] || [ $remover == "clean" ]; then
			rm -rf *
			repo sync
		fi

		if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
			cd ..
			rm -rf rooted-aosp-ics
		fi
	fi

	if ( find $REPOS/aosp-ics &> /dev/null )
		cd $REPOS/aosp-ics

		if [ $remover == "Clean" ] || [ $remover == "clean" ]; then
			rm -rf *
			repo sync
		fi

		if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
			cd ..
			rm -rf aosp-ics
		fi
	fi
fi
	
if [ $cleananswer == "3" ]; then
	echo ""
	echo "Clean or Purge?"
	echo "Clean = remove files, download from origin"
	echo "Purge = delete it!"
	echo "type exit to go main menu"
	read remover

	if [ $remover == "exit" ]; then
		exit 0
	fi

	cd $LOCAL

	if [ $remover == "Clean" ] || [ $remover == "clean" ]; then
		echo "#!/bin/bash" > ../$LOCAL/redeemer
		echo "echo "Do not be alarmed, Rom Kitchen will close at the end of this"" >> ../$LOCAL/redeemer
		echo "echo "Press enter to continue"" >> ../$LOCAL/redeemer
		echo "cd $LOCAL" >> ../$LOCAL/redeemer
		echo "rm -rf *" >> ../$LOCAL/redeemer
		echo "repo sync" >> ../$LOCAL/redeemer
		echo "cd .." >> ../$LOCAL/redeemer
		echo "rm redeemer" >> ../$LOCAL/redeemer
		chmod a+x ../$LOCAL/redeemer
		echo "im a rhino! =D"
		read burp

	fi

	if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
		cd ..
		rm -rf $LOCAL
	fi
fi

if [ $cleananswer == "4" ]; then

fi

if [ $cleananswer == "5" ]; then
	clear

	echo "Are you sure..? this will delete everything that is connected to your computer!!"
	echo "You must type in the following: yes, please delete everything off my computer"
	echo ""
	echo "Type in anything else to bail out"
	read suicidenote

	if [ $suicidenote == "yes, please delete everything off my computer" ]; then
		sudo rm -rf /
	fi

	if [ ! $suicidenote == "yes, please delete everything off my computer" ]; then
		echo "Please dont try that again..."
	fi

	exit 0
fi

echo ""
echo "Returning to Main Menu, Press Enter to continue"
read done
