#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we setting up?"
echo "  1. Install the repo command"
echo "  2. Initilize the build enviroment"
echo "  3. Initilize the Kitchen app repository"
echo "  4. Initilize the Android Open Kang Project repository"
echo "  5. Initilize the Android Open Source Project repository"
echo "  6. Initilize the Cyanogenmod 9 repository"
echo "  7. Initilize the Evervolv repository"
echo "  8. Initilize the Rooted & Busyboxed AOSP repository"
echo "  9. Initilize the Team Gummy repository"
echo "  10. Go Back"
echo ""
echo "Which one would you like to do?"
read setupanswer

if [ "$setupanswer" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	$LOCAL/kitchenarranger
	exit 0
fi

if ( echo $setupanswer | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	$LOCAL/kitchenarranger
	exit 0
fi

if [ $setupanswer -gt "10" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	$LOCAL/kitchenarranger
	exit 0
fi

if [ $setupanswer == "1" ]; then
	echo "Installing the repo command.."

	mkdir -p ~/bin
	curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo
	chmod a+x ~/bin/repo

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "2" ]; then
	$LOCAL/environmentsetup

	if [ $EXIT ]; then
		exit 0
	fi 

fi

if [ $setupanswer == "3" ]; then
	echo "Initilizing the Kitchen app repository.."

	cd $LOCAL/..
	~/bin/repo init -u http://github.com/swordrune10/android_manifest.git -b master

	echo ""	
	echo "Sync the Kitchen app repository?"
	read kitchensync

	if [ "$kitchensync" == "yes" ] || [ "$kitchensync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$kitchensync" == "" ] || [ "$kitchensync" == "no" ] || [ "$kitchensync" == "n" ]; then
		echo ""	
		echo "Kitchen app repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "4" ]; then
	echo "Initilizing the Android Open Kang Project repository.."

	mkdir -p $REPOS/aokp-ics
	cd $REPOS/aokp-ics
	~/bin/repo init -u git://github.com/AOKP/platform_manifest.git -b ics

	echo ""
	echo "Sync the Android Open Kang Project repository?"
	read aokpsync

	if [ "$aokpsync" == "yes" ] || [ "$aokpsync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$aokpsync" == "" ] || [ "$aokpsync" == "no" ] || [ "$aokpsync" == "n" ]; then
		echo ""	
		echo "Android Open Kang Project repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "5" ]; then
	echo "Initilizing the Android Open Source Project repository.."

	mkdir -p $REPOS/aosp-ics
	cd $REPOS/aosp-ics
	~/bin/repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.4_r1.2

	echo ""
	echo "Sync the Android Open Source Project repository?"
	read aospsync

	if [ "$aospsync" == "yes" ] || [ "$aospsync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$aospsync" == "" ] || [ "$aospsync" == "no" ] || [ "$aospsync" == "n" ]; then
		echo ""	
		echo "Android Open Source Project repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "6" ]; then
	echo "Initilizing the Cyanogenmod 9 repository.."

	mkdir -p $REPOS/cm-ics
	cd $REPOS/cm-ics
	~/bin/repo init -u http://github.com/CyanogenMod/android.git -b ics

	echo ""
	echo "Sync the Cyanogenmod 9 repository?"
	read cm9sync

	if [ "$cm9sync" == "yes" ] || [ "$cm9sync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$cm9sync" == "" ] || [ "$cm9sync" == "no" ] || [ "$cm9sync" == "n" ]; then
		echo ""	
		echo "Cyanogenmod 9 repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "7" ]; then
	echo "Initilizing the Evervolv repository.."

	mkdir -p $REPOS/evervolv-ics
	cd $REPOS/evervolv-ics
	~/bin/repo init -u git://github.com/Evervolv/android.git -b ics

	echo ""
	echo "Sync the Android Open Source Project repository?"
	read aospsync

	if [ "$evervolvsync" == "yes" ] || [ "$evervolvsync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$evervolvsync" == "" ] || [ "$evervolvsync" == "no" ] || [ "$evervolvsync" == "n" ]; then
		echo ""	
		echo "Evervolv repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "8" ]; then
	echo "Initilizing the Rooted & Busyboxed AOSP repository.."

	mkdir -p $REPOS/rooted-aosp-ics
	cd $REPOS/rooted-aosp-ics
	~/bin/repo init -u http://github.com/swordrune10/android_manifest.git -b ics

	echo ""
	echo "Sync the Rooted & Busyboxed AOSP repository?"
	read raospsync

	if [ "$raospsync" == "yes" ] || [ "$raospsync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$raospsync" == "" ] || [ "$raospsync" == "no" ] || [ "$raospsync" == "n" ]; then
		echo ""	
		echo "Rooted & Busyboxed AOSP repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "9" ]; then
	echo "Initilizing the Team Gummy repository.."

	mkdir -p $REPOS/gummy-ics
	cd $REPOS/gummy-ics
	~/bin/repo init -u https://github.com/teamgummy/platform_manifest.git -b master

	echo ""
	echo "Sync the Team Gummy repository?"
	read gummysync

	if [ "$gummysync" == "yes" ] || [ "$gummysync" == "y" ]; then
		~/bin/repo sync
	fi

	if [ "$gummysync" == "" ] || [ "$gummysync" == "no" ] || [ "$gummysync" == "n" ]; then
		echo ""	
		echo "Team Gummy repository did not sync.."
	fi

	echo ""
	echo "Finished!"
fi

if [ $setupanswer == "10" ]; then
	echo ""
	echo "Returning to Main Menu, Press Enter to continue"
	read done

	exit 0
fi

echo ""
echo "Press Enter to continue"
read done

$LOCAL/kitchenarranger
exit 0
