#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Today's Menu:"
echo "  1. Build Verizon Galaxy Nexus"
echo "  2. Build GSM Galaxy Nexus"
echo "  3. Build Sprint Galaxy Nexus"
echo "  4. Build all above!"
echo "  5. Build other..."
echo "  6. Go Back"
echo ""
echo "Which one would you like to do?"
read buildanswer

if [ $buildanswer == "1" ]; then
	./buildtoro
fi

if [ $buildanswer == "2" ]; then
	./buildmaguro
fi
	
if [ $buildanswer == "3" ]; then
	./buildtoroplus
fi

if [ $buildanswer == "4" ]; then
	./buildall
fi

if [ $buildanswer == "5" ]; then
	./buildother
fi

echo ""
echo "Returning to Main Menu, Press Enter to continue"
read done
