#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we updating?"
echo "  1. Update the Kitchen app repository"
echo "  2. Initilize the Android Open Kang Project repository"
echo "  3. Initilize the Android Open Source Project repository"
echo "  4. Initilize the Cyanogenmod 9 repository"
echo "  5. Initilize the Evervolv repository"
echo "  6. Initilize the Rooted & Busyboxed AOSP repository"
echo "  7. Initilize the Team Gummy repository"
echo "  8. All of the above"
echo "  9. Go Back"
read version

if [ "$version" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	$LOCAL/kitchenupdater
	exit 0
fi

if ( echo $version | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	$LOCAL/kitchenupdater
	exit 0
fi

if [ $version -gt "9" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done

	$LOCAL/kitchenupdater
	exit 0
fi

if [ $version == "1" ] || [ $version == "8" ]; then
	echo ""	
	echo "Updating the Kitchen app repository.."
	cd $LOCAL/..

	~/bin/repo sync -j8
	echo ""	
	echo "Kitchen Update Complete!"
fi

if [ $version == "2" ] || [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "aokp")
	echo ""	
	echo "Updating the Android Open Kang Project repository.."
	cd $REPOS/aokp-ics
	rm -r vendor/aokp

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/../gitpuller &> /dev/null ); then
		export AUTHOR="gitpuller"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../gitpuller
	fi

	$LOCAL/../gitpuller

	$LOCAL/postupdate

	if ( ! find $LOCAL/../romeditor &> /dev/null ); then
		export AUTHOR="romeditor"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../romeditor
	fi

	echo ""	
	echo "Android Open Kang Project Update Complete!"
fi

if [ $version == "3" ] || [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	echo ""	
	echo "Updating Android Open Source Project repository.."
	cd $REPOS/aosp-ics

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/../gitpuller &> /dev/null ); then
		export AUTHOR="gitpuller"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../gitpuller
	fi

	$LOCAL/../gitpuller

	$LOCAL/postupdate

	if ( ! find $LOCAL/../romeditor &> /dev/null ); then
		export AUTHOR="romeditor"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../romeditor
	fi

	echo ""	
	echo "Android Open Source Project Update Complete!"
fi

if [ $version == "4" ] || [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "evervolv")
	echo ""	
	echo "Updating Evervolv repository.."
	cd $REPOS/aosp-ics
	rm -r vendor/ev

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/../gitpuller &> /dev/null ); then
		export AUTHOR="gitpuller"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../gitpuller
	fi

	$LOCAL/../gitpuller

	$LOCAL/postupdate

	if ( ! find $LOCAL/../romeditor &> /dev/null ); then
		export AUTHOR="romeditor"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../romeditor
	fi

	echo ""	
	echo "Evervolv Update Complete!"
fi

if [ $version == "5" ] || [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "cm")
	echo ""	
	echo "Updating Cyanogenmod 9 repository.."
	cd $REPOS/cm-ics
	rm -r vendor/cm

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/../gitpuller &> /dev/null ); then
		export AUTHOR="gitpuller"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../gitpuller
	fi

	$LOCAL/../gitpuller

	$LOCAL/postupdate

	if ( ! find $LOCAL/../romeditor &> /dev/null ); then
		export AUTHOR="romeditor"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../romeditor
	fi

	echo ""	
	echo "Cyanogenmod 9 Update Complete!"
fi

if [ $version == "6" ] || [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "rooted-aosp")
	echo ""	
	echo "Updating Rooted & Busyboxed AOSP repository.."
	cd $REPOS/rooted-aosp-ics
	rm -r vendor/swordrune10

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/../gitpuller &> /dev/null ); then
		export AUTHOR="gitpuller"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../gitpuller
	fi

	$LOCAL/../gitpuller

	$LOCAL/postupdate

	if ( ! find $LOCAL/../romeditor &> /dev/null ); then
		export AUTHOR="romeditor"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../romeditor
	fi

	echo ""	
	echo "Rooted & Busyboxed AOSP Update Complete!"
fi

if [ $version == "7" ] || [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "gummy")
	echo ""	
	echo "Updating Team Gummy repository.."
	cd $REPOS/gummy-ics
	rm -r vendor/Gummy

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/../gitpuller &> /dev/null ); then
		export AUTHOR="gitpuller"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../gitpuller
	fi

	$LOCAL/../gitpuller

	$LOCAL/postupdate

	if ( ! find $LOCAL/../romeditor &> /dev/null ); then
		export AUTHOR="romeditor"
		$LOCAL/scriptmakir
		chmod a+x $LOCAL/../romeditor
	fi

	echo ""	
	echo "Team Gummy Update Complete!"
fi

if [ $version == "9" ]; then
	echo ""
	echo "Returning to Main Menu, Press Enter to continue"
	read done

	exit 0
fi

echo ""
echo "Press Enter to continue"
read done

$LOCAL/kitchenupdater
exit 0
