#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

if [ ! $loop ]; then
	export LOCAL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

cd $LOCAL

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Today's Menu:"
echo "  1. Setup Kitchen"
echo "  2. Update Kitchen"
echo "  3. Run Kitchen"
echo "  4. Exit"
echo ""
echo "Which one would you like to do?"

read answer

if [ $answer == "1" ]; then
	$LOCAL/.scripts/setupkitchen
	export loop=true
	$LOCAL/.scripts/kitchen
	exit 0
fi

if [ $answer == "2" ]; then
	$LOCAL/.scripts/updatekitchen
	export loop=true
	$LOCAL/.scripts/kitchen
	exit 0
fi

if [ $answer == "3" ]; then
	clear
	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Today's Menu:"
	echo "  1. Build Verizon Galaxy Nexus"
	echo "  2. Build GSM Galaxy Nexus"
	echo "  3. Build Sprint Galaxy Nexus"
	echo "  4. Build all above!"
	echo ""
	echo "Which one would you like to do?"
	read buildanswer

	if [ $buildanswer == "1" ]; then
		$LOCAL/.scripts/buildtoro
		export loop=true
		$LOCAL/.scripts/kitchen
		exit 0
	fi

	if [ $buildanswer == "2" ]; then
		$LOCAL/.scripts/buildmaguro
		export loop=true
		$LOCAL/.scripts/kitchen
		exit 0
	fi
	
	if [ $buildanswer == "3" ]; then
		$LOCAL/.scripts/buildtoroplus
		export loop=true
		$LOCAL/.scripts/kitchen
		exit 0
	fi

	if [ $buildanswer == "4" ]; then
		$LOCAL/.scripts/buildall
		export loop=true
		$LOCAL/.scripts/kitchen
		exit 0
	fi
fi

if [ $answer == "4" ]; then
	exit 0
fi

if [ $answer == "10" ]; then
	echo "You seem bored.. wanna watch a movie?"
	read nothing
	if [ $nothing == "no" ] || [ $nothing == "n" ]; then
		echo "tough!"
	fi
	telnet towel.blinkenlights.nl
fi
