#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

if [ ! $LOOP ]; then
	export LOCAL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

cd $LOCAL

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Main Menu:"
echo "  1. Setup Kitchen"
echo "  2. Update Kitchen"
echo "  3. Run Kitchen"
echo "  4. Fix Kitchen"
echo "  5. Exit"
echo ""
echo "Which one would you like to do?"

read answer

if [ $answer == "1" ]; then
	$LOCAL/.scripts/setupkitchen
	export LOOP=true
	$LOCAL/.scripts/kitchen
	exit 0
fi

if [ $answer == "2" ]; then
	$LOCAL/.scripts/updatekitchen
	export LOOP=true
	$LOCAL/.scripts/kitchen
	exit 0
fi

if [ $answer == "3" ]; then
	$LOCAL/.scripts/kitchenbuilder
	export LOOP=true
	$LOCAL/.scripts/kitchen
	exit 0
fi

if [ $answer == "4" ]; then
	$LOCAL/.scripts/kitchencleaner
	export LOOP=true
	$LOCAL/.scripts/kitchen
	exit 0
fi

if [ $answer == "10" ]; then
	echo "You seem bored.. wanna watch a movie?"
	read nothing
	if [ $nothing == "no" ] || [ $nothing == "n" ]; then
		echo "tough!"
	fi
	telnet towel.blinkenlights.nl
fi
