#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Something is not working right? What should we do?"
echo "Purge = remove files, download from origin"
echo "Delete = delete it!"
echo "  1. Purge/Delete a certain repository"
echo "  2. Purge/Delete all the repositories"
echo "  3. Purge/Delete the Kitchen app"
echo "  4. Delete the Kitchen app, and its dependencies"
echo "  5. Delete entire computer"
echo "  6. Go Back"
echo ""
echo "Which one would you like to do?"
read cleananswer

if [ $cleananswer == "1" ]; then
	clear

	echo "which repo would you like to modify?"
	echo "Cyanogenmod 9 = cm"
	echo "Rooted & Busyboxed AOSP = rooted-aosp"
	echo "Android Open Source Project = aosp"
	echo "type exit to go to back"
	read modify

	if [ $modify == "exit" ]; then
		echo ""
		echo "Press Enter to continue"
		read done

		$LOCAL/kitchencleaner
		exit 0
	fi

	echo ""
	echo "Purge or Delete?"
	echo "Purge = remove files, download from origin"
	echo "Delete = delete it!"
	echo "type exit to go to back"
	read remover

	if [ $remover == "exit" ]; then
		echo ""
		echo "Press Enter to continue"
		read done

		$LOCAL/kitchencleaner
		exit 0
	fi

	cd $REPOS/$modify-ics

	if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
		rm -rf *
		repo sync
	fi

	if [ $remover == "Delete" ] || [ $remover == "delete" ]; then
		cd ..
		rm -rf $modify-ics
	fi
	
fi

if [ $cleananswer == "2" ]; then
	clear

	echo "Purge or Delete the repositories?"
	echo "Purge = remove files, download from origin"
	echo "Delete = delete it!"
	echo "type exit to go to back"
	read remover

	if [ $remover == "exit" ]; then
		echo ""
		echo "Press Enter to continue"
		read done

		$LOCAL/kitchencleaner
		exit 0
	fi

	if ( find $REPOS/cm-ics &> /dev/null ); then
		cd $REPOS/cm-ics

		if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
			rm -rf *
			repo sync
		fi

		if [ $remover == "Delete" ] || [ $remover == "delete" ]; then
			cd ..
			rm -rf cm-ics
		fi
	fi

	if ( find $REPOS/rooted-aosp-ics &> /dev/null ); then
		cd $REPOS/rooted-aosp-ics

		if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
			rm -rf *
			repo sync
		fi

		if [ $remover == "Delete" ] || [ $remover == "delete" ]; then
			cd ..
			rm -rf rooted-aosp-ics
		fi
	fi

	if ( find $REPOS/aosp-ics &> /dev/null ); then
		cd $REPOS/aosp-ics

		if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
			rm -rf *
			repo sync
		fi

		if [ $remover == "Delete" ] || [ $remover == "delete" ]; then
			cd ..
			rm -rf aosp-ics
		fi
	fi

	echo ""
	echo "Finished!"
fi
	
if [ $cleananswer == "3" ]; then
	clear

	echo "Purge or Delete?"
	echo "Purge = remove files, download from origin"
	echo "Delete = delete it!"
	echo "type exit to go back"
	read remover

	if [ $remover == "exit" ]; then
		echo ""
		echo "Press Enter to continue"
		read done

		$LOCAL/kitchencleaner
		exit 0
	fi

	cd $LOCAL/..

	if [ $remover == "Purge" ] || [ $remover == "purge" ]; then
		export AUTHOR="redeemer"
		$LOCAL/scriptmakir

		chmod a+x redeemer
		echo ""
		echo "Switching to Redeemer script.."
		echo ""
		./redeemer
		echo ""
		echo "Finished!"
	fi

	if [ $remover == "Delete" ] || [ $remover == "delete" ]; then
		echo ""
		echo "Are you sure you want to remove the Kitchen app?"
		echo "You must type in \"yes\" to continue"
		echo ""
		echo "Type in anything else to abort operation"
		read destroyer

		if [ $destroyer == "yes" ]; then
			export AUTHOR="destroyer"
			$LOCAL/scriptmakir

			chmod a+x destroyer
			echo ""
			echo "Thank you for using Swordrune10's Kitchen!"
			echo "Switching to Destroyer script.."
			echo ""
			./destroyer
			exit 0
		fi
	fi
fi

if [ $cleananswer == "4" ]; then
	clear

	echo "Are you sure you want to remove the Kitchen app and its dependencies?"
	echo "Please note: the builds directory will not be deleted?"
	echo "You must type in \"yes\" to continue"
	echo ""
	echo "Type in anything else to abort operation"
	read destroyerofworlds

	if [ $destroyerofworlds == "yes" ]; then
		export AUTHOR="destroyerofworlds"
		$LOCAL/scriptmakir

		chmod a+x destroyerofworlds
		echo ""
		echo "Thank you for using Swordrune10's Kitchen!"
		echo "Switching to Destroyer of Worlds script.."
		echo ""
		./destroyerofworlds
		exit 0
	fi
fi

if [ $cleananswer == "5" ]; then
	clear

	echo "Are you sure..? this will delete everything on your computer, including external drives and flash drives!!"
	echo "You must type in \"yes, please delete everything off my computer\" to continue"
	echo ""
	echo "Type in anything else to bail out"
	read suicidenote

	if [ ! $suicidenote == "yes, please delete everything off my computer" ]; then
		echo "Please dont try that again..."
	fi

	if [ $suicidenote == "yes, please delete everything off my computer" ]; then
		echo "Please type in your password to destroy everything"		
		sudo rm -rf /
	fi

	echo ""
	echo "Finished!"
fi

if [ $cleananswer == "6" ]; then
	echo ""
	echo "Returning to Main Menu, Press Enter to continue"
	read done
	exit 0
fi

echo ""
echo "Press Enter to continue"
read done

$LOCAL/kitchencleaner
exit 0
