#!/bin/bash
# Written by Sean Donovan (swordrune10)
cd $REPOS/$SCRIPT_REPO-ics/.repo
if ( ! find local_manifest.xml &> /dev/null ); then
	if [ $SCRIPT_REPO == "cm" ]; then
		echo "Adding missing local_manifest.xml"
		cp $LOCAL/xml/cm9-local_manifest.xml ./local_manifest.xml		
		exit 0	
	fi

	echo "Adding missing local_manifest.xml"
	cp $LOCAL/xml/aosp-local_manifest.xml ./local_manifest.xml
fi
