#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ $repodefine == "kitchen" ]; then
	export SCRIPT_REPO=$(echo "kitchen")
	export REPO_PLATFORM=$(echo "master")
	repo_branch=$(echo "master")
	repo_name=$(echo "Kitchen app")
	repo_url=$(echo "http://github.com/TeamKeyblade/kitchen_manifest.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "aokp" ]; then
	export SCRIPT_REPO=$(echo "aokp")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kitkat")
	repo_name=$(echo "Android Open Kang Project")
	repo_url=$(echo "http://github.com/AOKP/platform_manifest.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "aosp43" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	export REPO_PLATFORM=$(echo "jb")
	repo_branch=$(echo "android-4.3.1_r1")
	repo_name=$(echo "Android Open Source Project 4.3")
	repo_url=$(echo "https://android.googlesource.com/platform/manifest")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "aosp" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "android-4.4.1_r1")
	repo_name=$(echo "Android Open Source Project 4.4")
	repo_url=$(echo "https://android.googlesource.com/platform/manifest")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "carbon" ]; then
	export SCRIPT_REPO=$(echo "carbon")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kk")
	repo_name=$(echo "Carbon")
	repo_url=$(echo "http://github.com/CarbonDev/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "cm10" ]; then
	export SCRIPT_REPO=$(echo "cm")
	export REPO_PLATFORM=$(echo "10.2")
	repo_branch=$(echo "stable/cm-10.2")
	repo_name=$(echo "Cyanogenmod 10.2")
	repo_url=$(echo "http://github.com/CyanogenMod/android.git")
	manifest_name=$(echo "cm-10.2.0.xml")
fi

if [ $repodefine == "cm" ]; then
	export SCRIPT_REPO=$(echo "cm")
	export REPO_PLATFORM=$(echo "11")
	repo_branch=$(echo "cm-11.0")
	repo_name=$(echo "Cyanogenmod 11")
	repo_url=$(echo "http://github.com/CyanogenMod/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "evervolv" ]; then
	export SCRIPT_REPO=$(echo "evervolv")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kitkat")
	repo_name=$(echo "Evervolv")
	repo_url=$(echo "http://github.com/Evervolv/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "omni" ]; then
	export SCRIPT_REPO=$(echo "omni")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "android-4.4")
	repo_name=$(echo "omnirom")
	repo_url=$(echo "http://github.com/omnirom/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "pacman" ]; then
	export SCRIPT_REPO=$(echo "pacman")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "pac-4.4")
	repo_name=$(echo "PAC-man")
	repo_url=$(echo "http://github.com/PAC-man/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "paranoid" ]; then
	export SCRIPT_REPO=$(echo "paranoid")
	export REPO_PLATFORM=$(echo "jb")
	repo_branch=$(echo "jb43")
	repo_name=$(echo "ParanoidAndroid")
	repo_url=$(echo "http://github.com/ParanoidAndroid/manifest.git")
	manifest_name=$(echo "default.xml")
fi
