#!/bin/bash
cd $LOCAL

if [ $AUTHOR == "xml" ] && [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "ics" ]; then

cat << EOF > xml/cm-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="CyanogenMod/android_kernel_samsung_tuna" path="kernel/samsung/tuna" remote="github" revision="ics" />
  <project name="CyanogenMod/android_device_samsung_tuna" path="device/samsung/tuna" remote="github" revision="ics" />
  <project name="CyanogenMod/android_device_samsung_toro" path="device/samsung/toro" remote="github" revision="ics" />
  <project name="CyanogenMod/android_device_samsung_maguro" path="device/samsung/maguro" remote="github" revision="ics" />
  <project name="CyanogenMod/android_device_samsung_toroplus" path="device/samsung/toroplus" remote="github" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_akm" path="vendor/akm" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_hp" path="vendor/hp" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_htc" path="vendor/htc" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_lge" path="vendor/lge" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_semc" path="vendor/semc" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_zte" path="vendor/zte" revision="ics" />
</manifest>
EOF

fi

if [ $AUTHOR == "xml" ] && [ $SCRIPT_REPO == "cm" ] || [ $SCRIPT_REPO == "paranoid" ] && [ $REPO_PLATFORM == "jb" ]; then

cat << EOF > xml/cm10-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="CyanogenMod/android_kernel_samsung_tuna" path="kernel/samsung/tuna" remote="github" revision="jb" />
  <project name="CyanogenMod/android_device_samsung_tuna" path="device/samsung/tuna" remote="github" revision="jellybean" />
  <project name="CyanogenMod/android_device_samsung_toro" path="device/samsung/toro" remote="github" revision="jellybean" />
  <project name="CyanogenMod/android_device_samsung_maguro" path="device/samsung/maguro" remote="github" revision="jellybean" />
  <project name="CyanogenMod/android_device_samsung_toroplus" path="device/samsung/toroplus" remote="github" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_akm" path="vendor/akm" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_hp" path="vendor/hp" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_htc" path="vendor/htc" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_lge" path="vendor/lge" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_semc" path="vendor/semc" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_zte" path="vendor/zte" revision="ics" />
</manifest>
EOF

fi

if [ $AUTHOR == "xml" ] && [ $SCRIPT_REPO == "aosp" ]; then

cat << EOF > xml/aosp-jb-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="github"
           fetch="http://github.com/" />
  <project name="TheMuppets/proprietary_vendor_akm" path="vendor/akm" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" remote="github" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" remote="github" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" revision="jellybean" />
</manifest>
EOF

fi

if [ $AUTHOR == "xml" ] && [ $SCRIPT_REPO == "raosp" ]; then

cat << EOF > xml/raosp-jb-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="TheMuppets/proprietary_vendor_akm" path="vendor/akm" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" remote="github" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" revision="ics" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" remote="github" revision="jellybean" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" revision="jellybean" />
</manifest>
EOF

fi

if [ $AUTHOR == "gitpuller" ]; then

cat << EOF > config/gitpuller
#!/bin/bash
if [ \$SCRIPT_REPO == "cm" ] && [ \$REPO_PLATFORM == "ics" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "cm" ] && [ \$REPO_PLATFORM == "jb" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "aokp" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "gummy" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "aosp" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "raosp" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi
EOF

chmod a+x config/gitpuller

fi

if [ $AUTHOR == "romeditor" ]; then

cat << EOF > config/romeditor
#!/bin/bash
if [ \$SCRIPT_REPO == "cm" ]; then
	cd \$REPOS/cm-\$REPO_PLATFORM/vendor/cm/config
	sed -i 's/developerid=cyanogenmod/developerid=\$(shell whoami)/g' common.mk
	sed -i 's/CM_BUILDTYPE := UNOFFICIAL/CM_BUILDTYPE := SWORDKITCHEN/g' common.mk
	sed -i 's/shell date -u +%Y%m%d/shell date +%Y%m%d/g' common.mk
fi

if [ \$SCRIPT_REPO == "raosp" ]; then
	cd \$REPOS/rooted-aosp-ics/vendor/keyblade/makefiles
	# uncomment (remove the #) and edit the EDITME! in between the slashes with ur rom manager developer id
	# sed -i 's/developerid=teamkeyblade/EDITME!/g' overrider.mk
	# uncomment (remove the #) and edit the EDITME! in between the slashes with the desired modversion (used for rom manager)
	# sed -i 's/\$(MOD_VERSION)/EDITME!/g' overrider.mk
fi
EOF

chmod a+x config/romeditor

fi

if [ $AUTHOR == "redeemer" ]; then

cat << EOF > ../redeemer
#!/bin/bash
echo "Redeemer is running!"
echo ""
echo "Removing Kitchen"
echo ""
rm -rf .repo
rm -rf .scripts
rm -f swordkitchen.sh
echo "Settng Up Kitchen"
echo ""
repo init -u http://github.com/TeamKeyblade/android_manifest.git -b stable
repo sync
EOF

chmod a+x ../redeemer

fi

if [ $AUTHOR == "destroyer" ] || [ $AUTHOR == "destroyerofworlds" ]; then

cat << START > ../$AUTHOR
#!/bin/bash
START

if [ $AUTHOR == "destroyer" ]; then
cat << TITLE >> ../$AUTHOR
echo "Destroyer is running!"
TITLE
fi

if [ $AUTHOR == "destroyerofworlds" ]; then
cat << TITLE >> ../$AUTHOR
echo "Destroyer of Worlds is running!"
TITLE
fi

cat << BODY >> ../$AUTHOR
echo ""
echo "Removing Kitchen"
echo ""
rm -rf .repo
rm -rf \$LOCAL
rm -f swordkitchen.sh
BODY

if [ $AUTHOR == "destroyerofworlds" ]; then
cat << DESTROYREPOS >> ../$AUTHOR
echo "Removing Repository folder"
echo ""
rm -rf \$REPOS
DESTROYREPOS
fi

cat << EOF >> ../$AUTHOR
echo "Finished! Press Enter to exit"
read done
rm -f ../$AUTHOR
EOF

chmod a+x ../$AUTHOR

fi
