#!/bin/bash
if [ $AUTHOR == "gitpuller" ]; then
	echo "#!/bin/bash" > ../gitpuller
	echo "if [ $SCRIPT_REPO == \"cm\" ]; then" >> ../gitpuller
	echo "	# below is examples, git pull is recommended" >> ../gitpuller
	echo "	# cd $REPOS/cm-ics/where-in-the-repo-you-want-to-modify" >> ../gitpuller
	echo "	# git pull repo-you-want-to-pull" >> ../gitpuller
	echo "	exit 0" >> ../gitpuller
	echo "fi" >> ../gitpuller
	echo "" >> ../gitpuller
	echo "if [ $SCRIPT_REPO == \"aosp\" ]; then" >> ../gitpuller
	echo "	# below is examples, git pull is recommended" >> ../gitpuller
	echo "	# cd $REPOS/cm-ics/where-in-the-repo-you-want-to-modify" >> ../gitpuller
	echo "	# git pull repo-you-want-to-pull" >> ../gitpuller
	echo "	exit 0" >> ../gitpuller
	echo "fi" >> ../gitpuller
	echo "" >> ../gitpuller
	echo "if [ $SCRIPT_REPO == \"rooted-aosp\" ]; then" >> ../gitpuller
	echo "	# below is examples, git pull is recommended" >> ../gitpuller
	echo "	# cd $REPOS/cm-ics/where-in-the-repo-you-want-to-modify" >> ../gitpuller
	echo "	# git pull repo-you-want-to-pull" >> ../gitpuller
	echo "	exit 0" >> ../gitpuller
	echo "fi" >> ../gitpuller
fi

if [ $AUTHOR == "redeemer" ]; then
	echo "#!/bin/bash" > redeemer
	echo "echo \"Redeemer is running!\"" >> redeemer
	echo "echo \"\"" >> redeemer
	echo "echo \"Removing Kitchen\"" >> redeemer
	echo "echo \"\"" >> redeemer
	echo "rm -rf .repo" >> redeemer
	echo "rm -rf .scripts" >> redeemer
	echo "rm -f \"Swordrune10's Kitchen.sh\"" >> redeemer
	echo "echo \"Settng Up Kitchen\"" >> redeemer
	echo "echo \"\"" >> redeemer
	echo "repo init -u http://github.com/swordrune10/android_manifest.git -b master" >> redeemer
	echo "repo sync" >> redeemer
	echo "cd $LOCAL" >> redeemer
	echo "echo \"Finished! Press Enter to restart Kitchen\"" >> redeemer
	echo "read done" >> redeemer
fi

if [ $AUTHOR == "destroyer" ] || [ $AUTHOR == "destroyerofworlds" ]; then
	echo "#!/bin/bash" > $AUTHOR

	if [ $AUTHOR == "destroyer" ]; then
		echo "echo \"Destroyer is running!\"" >> destroyer
	fi

	if [ $AUTHOR == "destroyerofworlds" ]; then
		echo "echo \"Destroyer of Worlds is running!\"" >> destroyerofworlds
	fi

	echo "echo \"\"" >> $AUTHOR
	echo "echo \"Removing Kitchen\"" >> $AUTHOR
	echo "echo \"\"" >> $AUTHOR
	echo "rm -rf .repo" >> $AUTHOR
	echo "rm -rf .scripts" >> $AUTHOR
	echo "rm -f \"Swordrune10's Kitchen.sh\"" >> $AUTHOR
	echo "rm -f gitpuller" >> $AUTHOR

	if [ $AUTHOR == "destroyerofworlds" ]; then
		echo "rm -rf ../repos" >> destroyerofworlds
	fi

	echo "echo \"Finished! Press Enter to exit\"" >> $AUTHOR
	echo "read done" >> $AUTHOR
	echo "rm -f $AUTHOR" >> $AUTHOR
fi
