#!/bin/bash
echo "Would you like the Cyanogenmod 9 repository?"
read cm9
if [ $cm9 == "yes" ] || [ $cm9 == "y" ]; then
	mkdir -p $local/repos/cm-ics
	cd $local/repos/cm-ics
	repo init -u http://github.com/CyanogenMod/android.git -b ics
fi

echo "Would you like the Android Open Source Project repository?"
read aosp
if [ $aosp == "yes" ] || [ $aosp == "y" ]; then
	mkdir -p $local/repos/cm-ics
	cd $local/repos/aosp-ics
	repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.4_r1.2
fi

echo "Lets sync up the new repos, shall we?"
read sync
if [ $sync == "yes" ] || [ $sync == "y" ]; then
updatekitchen
fi

cd $local

echo "done!"
