#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

romeditor

cd $REPOS/$SCRIPT_REPO-ics
. build/envsetup.sh

if [ $AUTO ]; then
	make clobber
	exit 0
fi

echo "clean out folder?"
read purgeout

if [ "$purgeout" == "" ]; then
	echo ""
	echo "Did you just hit enter without a care? for that im just gonna clean the folder anyways.."

	make clobber
fi

if [ $purgeout == "yes" ] || [ $purgeout == "y" ]; then
	make clobber
fi
