#!/bin/bash
# Written by Sean Donovan (swordrune10)
cd $REPOS/../builds
builddir=$( pwd )

cd $REPOS/$SCRIPT_REPO-ics/out/target/product/$SCRIPT_DEVICE

if [ $SCRIPT_REPO == "cm" ]; then
	zip=$(find update*.zip)
fi

if [ $SCRIPT_REPO == "aokp" ]; then
	zip=$(find aokp*.zip)
fi

if [ $SCRIPT_REPO == "evervolv" ]; then
	zip=$(find Evervolv*.zip)
fi

if [ $SCRIPT_REPO == "sts" ]; then
	zip=$(find *CM9*.zip)
fi

if [ $SCRIPT_REPO == "gummy" ]; then
	zip=$(find Gummy*.zip)
fi

if [ $SCRIPT_REPO == "aosp" ] || [ $SCRIPT_REPO == "rooted-aosp" ]; then
	zip=$(find full*.zip)

	echo "Making temporary folder for post-building $zip fixes"
	mkdir -p $builddir/temp/zipout
	cp $zip $builddir/temp
	cd $builddir/temp/zipout

	echo "Unzipping $zip"
	unzip ../$zip > /dev/null

	echo "Removing uneeded recovery folder from $zip"
	rm -r recovery

	if [ $SCRIPT_REPO == "aosp" ]; then
		cd system
		echo "Adding rom manager items to $zip's build.prop"
		echo "ro.rommanager.developerid=$(whoami)" >> build.prop
		echo "ro.modversion=$(echo "aosp-ics-$(date +%Y%m%d)-$SCRIPT_DEVICE")" >> build.prop

		cd ..
	fi

	echo "Zipping $zip back up"
	zip -r unsignedcrap.zip . > /dev/null

	echo "Signing $zip with test keys"
	java -Xmx1024m -classpath $LOCAL/testsign.jar testsign unsignedcrap.zip $zip
fi

mkdir -p $builddir/$SCRIPT_REPO/old

if ( find $builddir/$SCRIPT_REPO/*$SCRIPT_DEVICE.zip &> /dev/null); then
	echo "Moving older build to $builddir/$SCRIPT_REPO/old"

	mv $builddir/$SCRIPT_REPO/*$SCRIPT_DEVICE.zip $builddir/$SCRIPT_REPO/old
	mv $builddir/$SCRIPT_REPO/*$SCRIPT_DEVICE.zip.md5sum $builddir/$SCRIPT_REPO/old
fi

newzip=$(echo $SCRIPT_REPO-ics-$(date +%Y%m%d)-SWORDKITCHEN-$SCRIPT_DEVICE.zip)

echo "Copying to $builddir/$SCRIPT_REPO"
echo "$zip -> $newzip"
cp $zip $builddir/$SCRIPT_REPO/$newzip

if [ $SCRIPT_REPO == "aosp" ] || [ $SCRIPT_REPO == "rooted-aosp" ]; then
	echo "Cleaning up temporary folder"
	cd $builddir
	rm -r temp
fi

cd $builddir/$SCRIPT_REPO
md5sum $newzip
md5sum $newzip > $newzip.md5sum
