#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear
export REPOS=$(echo "$LOCAL/../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="

if ( ! find $REPOS &> /dev/null ); then
if ( ! find ~/bin/repo &> /dev/null ); then
	echo "I am assuming u already setup the build enviroment, if you haven't please stop now and do that.."
	echo "Hit Enter to continue"
	read pause

	echo "Lets install the repo command, shall we?"
	read repo
	if [ $repo == "yes" ] || [ $repo == "y" ]; then
		mkdir -p ~/bin
		curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo
		chmod a+x ~/bin/repo
	fi
fi
fi

if ( ! find $LOCAL/.repo &> /dev/null ); then
	echo ""
	echo "Lets initilize the kitchen repository, shall we?"
	read kitchen
	if [ $kitchen == "yes" ] || [ $kitchen == "y" ]; then
		cd $LOCAL
		repo init -u http://github.com/swordrune10/android_manifest.git  -b master
	fi
fi

if ( ! find $REPOS/cm-ics/.repo &> /dev/null ); then
	echo ""
	echo "Would you like the Cyanogenmod 9 repository?"
	read cm9
	if [ $cm9 == "yes" ] || [ $cm9 == "y" ]; then
		mkdir -p $REPOS/cm-ics
		cd $REPOS/cm-ics
		repo init -u http://github.com/CyanogenMod/android.git -b ics
	fi
fi

if ( ! find $REPOS/aosp-ics/.repo &> /dev/null ); then
	echo ""
	echo "Would you like the Android Open Source Project repository?"
	read aosp
	if [ $aosp == "yes" ] || [ $aosp == "y" ]; then
		mkdir -p $REPOS/aosp-ics
		cd $REPOS/aosp-ics
		repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.4_r1.2
	fi
fi

echo "Lets sync up the new repos, shall we?"
read sync
if [ $sync == "yes" ] || [ $sync == "y" ]; then
	$LOCAL/.scripts/updatekitchen
fi

echo ""
echo "Press Enter to continue"
read done
