#!/bin/bash
# Written by Sean Donovan (swordrune10)
cd $REPOS/$SCRIPT_REPO-ics/out/target/product/$SCRIPT_DEVICE
builddir=$(echo "$REPOS/../builds")

if [ $SCRIPT_REPO == "cm" ] || [ $SCRIPT_REPO == "sts" ]; then
	zip=$(find update*.zip)
fi

if [ $SCRIPT_REPO == "aokp" ]; then
	zip=$(find aokp*.zip)
fi

if [ $SCRIPT_REPO == "evervolv" ]; then
	zip=$(find Evervolv*.zip)
fi

if [ $SCRIPT_REPO == "gummy" ]; then
	zip=$(find Gummy*.zip)
fi

if [ $SCRIPT_REPO == "aosp" ] || [ $SCRIPT_REPO == "rooted-aosp" ]; then
	zip=$(find full*.zip)

	mkdir -p $builddir/temp/zipout
	cp $zip $builddir/temp
	cd $builddir/temp/zipout

	unzip ../$zip

	rm -r recovery

	if [ $SCRIPT_REPO == "aosp" ]; then
		cd system
		echo "ro.rommanager.developerid=$(whoami)" >> build.prop
		echo "ro.modversion=$(echo "aosp-ics-$(date +%Y%m%d)-$SCRIPT_DEVICE")" >> build.prop
		
		cd ..
	fi

	zip -r $zip .
fi

mkdir -p $builddir/$SCRIPT_REPO/old
mv $builddir/$SCRIPT_REPO/*$SCRIPT_DEVICE.zip $builddir/$SCRIPT_REPO/old &> /dev/null
mv $builddir/$SCRIPT_REPO/*$SCRIPT_DEVICE.zip.md5sum $builddir/$SCRIPT_REPO/old &> /dev/null

newzip=$(echo $SCRIPT_REPO-ics-$(date +%Y%m%d)-SWORDKITCHEN-$SCRIPT_DEVICE.zip)

cp $zip $builddir/$SCRIPT_REPO/$newzip

if [ $SCRIPT_REPO == "aosp" ] || [ $SCRIPT_REPO == "rooted-aosp" ]; then
	cd $builddir
	rm -r temp
fi

cd $builddir/$SCRIPT_REPO
md5sum $newzip > $newzip.md5sum
