#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear
export REPOS=$(echo "$LOCAL/../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Which version of android are we syncing?"
echo "  1. Cyanogenmod 9"
echo "  2. AOSP"
echo "  3. Kitchen"
echo "  4. All of the above"
echo "  5. Go Back"
read version

if [ ! $version == "5" ]; then
	clear
fi

if [ $version == "1" ] || [ $version == "4" ]; then
	export SCRIPT_REPO=$(echo "cm")
	echo "Syncing Cyanogenmod 9 repo"
	cd $REPOS/cm-ics
	rm -r vendor/cm

	$LOCAL/.scripts/preupdate
	~/bin/repo sync -j8

	if ( find $LOCAL/.scripts/repomod &> /dev/null ); then
		$LOCAL/.scripts/repomod
	fi

	$LOCAL/.scripts/postupdate
	echo "Cyanogenmod 9 Update Complete!"
fi

if [ $version == "2" ] || [ $version == "4" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	echo "Syncing AOSP repo"
	cd $REPOS/aosp-ics

	$LOCAL/.scripts/preupdate
	~/bin/repo sync -j8
	$LOCAL/.scripts/postupdate
	echo "AOSP Update Complete!"
fi

if [ $version == "3" ] || [ $version == "4" ]; then
	echo "Syncing Kitchen repo"
	cd $LOCAL/.scripts

	~/bin/repo sync -j8
	echo "Kitchen Update Complete!"
fi

echo ""
echo "Press Enter to continue"
read done
