#!/bin/bash
# Written by Sean Donovan (swordrune10)
clear

export REPOS=$(echo "$LOCAL/../../repos")
echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we updating?"
echo "  1. Kitchen"
echo "  2. Cyanogenmod 9"
echo "  3. Rooted & Busyboxed AOSP"
echo "  4. Pure AOSP"
echo "  5. All of the above"
echo "  6. Go Back"
read version

if [ ! $version == "6" ]; then
	clear
fi

if [ $version == "1" ] || [ $version == "5" ]; then
	echo "Updating Kitchen app"
	cd ..$LOCAL

	~/bin/repo sync -j8
	echo "Kitchen Update Complete!"
fi

if [ $version == "2" ] || [ $version == "5" ]; then
	export SCRIPT_REPO=$(echo "cm")
	echo "Updating Cyanogenmod 9 repository"
	cd $REPOS/cm-ics
	rm -r vendor/cm

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/gitpuller &> /dev/null ); then
		ln -s $LOCAL/gitpuller $LOCAL/../gitpuller
	fi

	$LOCAL/gitpuller

	$LOCAL/postupdate
	echo "Cyanogenmod 9 Update Complete!"
fi

if [ $version == "3" ] || [ $version == "5" ]; then
	export SCRIPT_REPO=$(echo "rooted-aosp")
	echo "Updating Rooted & Busyboxed AOSP repository"
	cd $REPOS/rooted-aosp-ics

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/gitpuller &> /dev/null ); then
		ln -s $LOCAL/gitpuller $LOCAL/../gitpuller
	fi

	$LOCAL/gitpuller

	$LOCAL/postupdate
	echo "Rooted & Busyboxed AOSP Update Complete!"
fi

if [ $version == "4" ] || [ $version == "5" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	echo "Updating AOSP repository"
	cd $REPOS/aosp-ics

	$LOCAL/preupdate
	~/bin/repo sync -j8

	if ( ! find $LOCAL/gitpuller &> /dev/null ); then
		ln -s $LOCAL/gitpuller $LOCAL/../gitpuller
	fi

	$LOCAL/gitpuller

	$LOCAL/postupdate
	echo "AOSP Update Complete!"
fi

echo ""
echo "Press Enter to continue"
read done
