#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Japanese

## THIS WHOLE FILE NEEDS TO BE RETRANSLATED, USED GOOGLE TRANSLATE! ##

## Common
export KITCHENTITLE=$( echo "Swordrune10のアンドロイドキッチン！" )
export KITCHENUNDERLINE=$( echo "===================================" )
export MENUGOBACK=$( echo "戻る" )
export NOTPROPERSELECTION=$( echo "あなたが適切な選択をしなかった、もう一度試してみてください！" )
export ENTERTOCONTINUE=$( echo "Enterキーを押して続行します： " )
export MAINMENURETURN=$( echo "メインメニューに戻ると、Enterキーを押して続行します： " )
export COMPLETEDMESSAGE=$( echo "完成！" )
export ANSWERYES=$( echo "はい" )
export ANSWERY=$( echo "h" )
export ANSWERNO=$( echo "いいえ" )
export ANSWERN=$( echo "ī" )

## Repos
export REPOSKITCHEN=$( echo "キッチンアプリ" )
export REPOSAOKP=$( echo "Android Open Kang Project" )
export REPOSAOSP43=$( echo "Android Open Source Project 4.3" )
export REPOSAOSP=$( echo "Android Open Source Project 4.4" )
export REPOSCARBON=$( echo "Carbon" )
export REPOSCM10=$( echo "Cyanogenmod 10.2" )
export REPOSCM=$( echo "Cyanogenmod 11" )
export REPOSEV=$( echo "Evervolv" )
export REPOSOMNI=$( echo "omnirom" )
export REPOSPACMAN=$( echo "PAC-man" )
export REPOSPARA=$( echo "ParanoidAndroid" )

## Kitchen
export KITCHENMAINMENU=$( echo "メインメニュー：" )
export KITCHENMENU1=$( echo "  1. セットアップ/更新キッチン" )
export KITCHENMENU2=$( echo "  2. を構成キッチン" )
export KITCHENMENU3=$( echo "  3. ランキッチン" )
export KITCHENMENU4=$( echo "  4. キッチンを修正しました" )
export KITCHENMENU5=$( echo "  5. 自動的にキッチンを構築" )
export KITCHENMENU6=$( echo "  6. 出口" )
export KITCHENMENUWHICH=$( echo "あなたはどちらが必要ですか？" )
export KITCHENTHANKS=$( echo "Swordrune10のキッチンをご利用いただきありがとうございます！さよなら.." )
export KITCHENBORED=$( echo "あなたは退屈に見える..たくは映画を見る？" )
export KITCHENTOUGH=$( echo "タフ！" )

## Reposync
# Usage and Flags
export REPOSYNCUSAGE=$( echo "レポ -- Androidのレポを初期化し、更新するためのプログラム" )
export REPOSYNCFLAGD=$( echo "適切なフォルダ、その後出口プログラムを削除" )
export REPOSYNCFLAGH=$( echo "このヘルプテキストを表示" )
export REPOSYNCFLAGP=$( echo "その後、パージフォルダ、再初期化、および更新" )
export REPOSYNCFLAGU=$( echo "この特定のレポを更新" )
export REPOSYNCUPDATE1=$( echo "アップデート $REPOSKITCHEN" )
export REPOSYNCUPDATE2=$( echo "アップデート $REPOSAOKP" )
export REPOSYNCUPDATE3=$( echo "アップデート $REPOSAOSP43" )
export REPOSYNCUPDATE4=$( echo "アップデート $REPOSAOSP" )
export REPOSYNCUPDATE5=$( echo "アップデート $REPOSCARBON" )
export REPOSYNCUPDATE6=$( echo "アップデート $REPOSCM10" )
export REPOSYNCUPDATE7=$( echo "アップデート $REPOSCM" )
export REPOSYNCUPDATE8=$( echo "アップデート $REPOSEV" )
export REPOSYNCUPDATE9=$( echo "アップデート $REPOSOMNI" )
export REPOSYNCUPDATE10=$( echo "アップデート $REPOSPACMAN" )
export REPOSYNCUPDATE11=$( echo "アップデート $REPOSPARA" )
export REPOSYNCUPDATE12=$( echo "使用可能なすべてのリポジトリを更新する" )
export REPOSYNCUPDATE13=$( echo "すべてのリポジトリを更新する" )
export REPOSYNCUSAGEEXAMP=$( echo "例： reposync -u cm-10.2" )
export REPOSYNCUSAGELIST1=$( echo "タイピング \"reposync -u list\" 与える" )
export REPOSYNCUSAGELIST2=$( echo "もしオプションリストを再び" )

# Menu
export REPOSYNCMENUWHAT=$( echo "私たちは何を更新している？" )
export REPOSYNCMENUINIT=$( echo "レポが初期化されていない場合には、更新時になり" )
export REPOSYNCMENU1=$( echo "レポコマンドをインストール" )
export REPOSYNCMENU2=$( echo "設定ビルド環境" )
export REPOSYNCMENU3=$( echo "更新 $REPOSKITCHEN 倉庫" )
export REPOSYNCMENU4=$( echo "更新 $REPOSAOKP 倉庫" )
export REPOSYNCMENU5=$( echo "更新 $REPOSAOSP43 倉庫" )
export REPOSYNCMENU6=$( echo "更新 $REPOSAOSP 倉庫" )
export REPOSYNCMENU7=$( echo "更新 $REPOSCARBON 倉庫" )
export REPOSYNCMENU8=$( echo "更新 $REPOSCM10 倉庫" )
export REPOSYNCMENU9=$( echo "更新 $REPOSCM 倉庫" )
export REPOSYNCMENU10=$( echo "更新 $REPOSEV 倉庫" )
export REPOSYNCMENU11=$( echo "更新 $REPOSOMNI 倉庫" )
export REPOSYNCMENU12=$( echo "更新 $REPOSPACMAN 倉庫" )
export REPOSYNCMENU13=$( echo "更新 $REPOSPARA 倉庫" )
export REPOSYNCMENU14=$( echo "使用可能なすべてのリポジトリを更新する" )
export REPOSYNCMENU15=$( echo "すべてのリポジトリを更新！" )
export REPOSYNCMENU16=$( echo "アップデート/ otherrepo追加" )

# Sync and Init
export REPOSYNCNOTINITSKIP=$( echo "スキップ、初期化されていません" )
export REPOSYNCUPDATING=$( echo "更新" )
export REPOSYNCBLAHSMANIFEST=$( echo "のマニフェスト" )
export REPOSYNCNOTINITYET=$( echo "今初期化し、初期化されていません" )
export REPOSYNCNOTINITWANTTO=$( echo "初期化されていない、あなたはそれを初期化したいのですか？" )
export REPOSYNCINIT=$( echo "初期化" )
export REPOSYNCNOTINIT=$( echo "初期化されませんでした" )
export REPOSYNCREPO=$( echo "倉庫" )
export REPOSYNCREPOALREADY=$( echo "レポコマンドが既にインストールされています" )
export REPOSYNCREPOINSTALL=$( echo "レポコマンドのインストール" )
export REPOSYNCCOMPLETE=$( echo "完全な更新！" )

# Otherrepo Sync and Init
export REPOSYNCADDOR=$( echo "我々は、追加またはotherrepo更新している？" )
export REPOSYNCOTHERMENU1=$( echo "カスタムレポフォルダに追加" )
export REPOSYNCOTHERMENU2=$( echo "すべてのカスタムリポジトリを更新" )
export REPOSYNCOTHERREPONAME=$( echo "レポの名前は何ですか？" )
export REPOSYNCOTHERREPOSHORTNAME=$( echo "このレポの短い名前は何ですか？例： Android Open Source Project = aosp" )
export REPOSYNCOTHERREPOURL=$( echo "レポのマニフェストへのURLとは何ですか？" )
export REPOSYNCOTHERREPOBRANCH=$( echo "使用したいブランチレポのマニフェストとは何ですか？" )
