#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dutch

## Common
export KITCHENTITLE=$( echo "Swordrune10's Android Kitchen!" )
export KITCHENUNDERLINE=$( echo "==============================" )
export MENUGOBACK=$( echo "Ga terug" )
export NOTPROPERSELECTION=$( echo "Je hebt geen geldige selectie gemaakt, probeer opnieuw!" )
export ENTERTOCONTINUE=$( echo "Druk op Enter om door te gaan: " )
export MAINMENURETURN=$( echo "Gaat terug naar hoofd menu, druk op Enter om door te gaan: " )
export ABORTMESSAGE=$( echo "Afbreken.." )
export COMPLETEDMESSAGE=$( echo "Klaar!" )
export QUESTIONYESNO=$( echo "ja/nee? " )
export ANSWERYES=$( echo "ja" )
export ANSWERY=$( echo "j" )
export ANSWERNO=$( echo "nee" )
export ANSWERN=$( echo "n" )

## Macosxinit
export MACOSXINITRUN=$( echo "U draait Mac OS X!" )
export MACOSXINITCANTFINDDMG=$( echo "We kunnen de android image om te mounten niet vinden, Dit is nodig om te bouwen op mac os x
Als je er al ‚‚n hebt gemaakt zet het dan op de juiste plaats met de juiste benaming
Zijn juiste plaats en benaming is in uw home map genaamd android.dmg, voorbeeld is ~/android.dmg

Wil je een nieuwe android.dmg maken?" )
export MACOSXINITHOWBIG=$( echo "Hoe groot wil je android.dmg maken? Houd in gedachten dat het zijn volume zal vergroten als je meer plaats nodig hebt
Type een nummer in gigabytes" )
export MACOSXINITMOUNTNEW=$( echo "Mounten van nieuw android.dmg in /Volumes/android.." )
export MACOSXINITMOVEINTO=$( echo "Verhuizen naar android.dmg.." )
export MACOSXINITSETUP=$( echo "Opzetten van keuken.." )
export MACOSXINITSETUP=$( echo "Opzetten van keuken.." )
export MACOSXINITFOUNDDMG=$( echo "Uw android.dmg is gevonden, mounten.." )
export MACOSXINITCANTFINDKITCHEN=$( echo "We kunnen de rom kitchen niet vinden in /Volumes/android

Zou je de rom kitchen willen installeren in /Volumes/android?" )

## Errors
export ERRORHEADER=$( echo "Er heeft zich een fout voorgedaan!
======================" )
export ERRORSIDEEFFECTS=$( echo "Neveneffecten kunnen onmogelijkheid zijn om goed te bouwen en gebrek aan ondersteuning
Voor de bouw-omgeving set-up" )
export ERRORCONTACTINFO=$( echo "Als u dit foutief ziet, laat het me dan weten op xda of rootzwiki
Als je liever een mailtje stuurt kan je me bereiken op mishana@swordrune10.net
Als je ook geneigd bent, ik heb een freenode kanaal #Swordrune10Kitchen" )
export BOUNCERPOWERPC=$( echo "PowerPC processor gedetecteerd!
===========================
Draaien van powerpc is niet echt verboden, maar het is niet aangeraden" )
export BOUNCER32BIT=$( echo "32-bit processor gedetecteerd!
==========================
Draaien van 32-bit is niet echt verboden, maar het is niet aangeraden" )
export BOUNCERKITCHENHOME=$( echo "Keuken is niet ingesteld op de juiste plaats!
=================================
De keuken zal niet correct werken als hij in de home map geplaatst is, verplaats alstublieft" )
export ENVIRONMENTSETUP32BIT=$( echo "32-bit niet ondersteund!
=====================
Bouw omgeving installatie ondersteund enkel 64-bit systemen" )
export ENVIRONMENTSETUPNOTSUPPORTED=$( echo "Besturingssysteem niet ondersteund!
===============================
Ondersteunde besturingssystemen(enkel 64-bit):
Ubuntu 10.04 - 14.04 (Volledige ondersteuning)
Debian (Algemene ondersteuning)
Linux Mint (Algemene ondersteuning)
Arch Linux (Algemene ondersteuning)
Fedora (Algemene ondersteuning)
Mac OS X (Half-Algemene ondersteuning)" )

## Repos
export REPOSKITCHEN=$( echo "Kitchen app" )
export REPOSAOKP=$( echo "Android Open Kang Project" )
export REPOSAOSP43=$( echo "Android Open Source Project 4.3" )
export REPOSAOSP=$( echo "Android Open Source Project 4.4" )
export REPOSCARBON=$( echo "Carbon" )
export REPOSCM10=$( echo "Cyanogenmod 10.2" )
export REPOSCM=$( echo "Cyanogenmod 11" )
export REPOSEV=$( echo "Evervolv" )
export REPOSOMNI=$( echo "omnirom" )
export REPOSPACMAN=$( echo "PAC-man" )
export REPOSPARA=$( echo "ParanoidAndroid" )

## Devices
export NEXUS4=$( echo "GSM Nexus 4" )
export NEXUS5=$( echo "LTE Nexus 5" )
export GSMGNEXUS=$( echo "GSM Galaxy Nexus" )
export SPRGNEXUS=$( echo "Sprint Galaxy Nexus" )
export VZWGNEXUS=$( echo "Verizon Galaxy Nexus" )
export ALLGNEXUS=$( echo "Alle Galaxy Nexi" )
export GSMNEXUSS=$( echo "GSM Nexus S" )
export SPRNEXUSS=$( echo "Sprint Nexus S 4G" )
export ALLNEXUSS=$( echo "Alle Nexus S'" )
export WIFINEXUS72012=$( echo "Wifi Nexus 7 (2012) Tablet" )
export GSMNEXUS72012=$( echo "GSM Nexus 7 (2012) Tablet" )
export ALLNEXUS72012=$( echo "Alle Nexus 7 (2012) Tablets" )
export WIFINEXUS72013=$( echo "Wifi Nexus 7 (2013) Tablet" )
export LTENEXUS72013=$( echo "LTE Nexus 7 (2013) Tablet" )
export ALLNEXUS72013=$( echo "Alle Nexus 7 (2013) Tablets" )
export ALLNEXUS7=$( echo "Alle Nexus 7 Tablets" )
export NEXUS10=$( echo "Wifi Nexus 10" )
export WIFIXOOM=$( echo "Wifi Xoom Tablet" )
export VZWXOOM=$( echo "Verizon Xoom Tablet" )
export ALLXOOM=$( echo "Alle Xoom Tablets" )
export ALLNEXUS=$( echo "Alle Nexus Devices" )

## Scriptmakir
export SCRIPTMAKIRREDEEMER=$( echo "Verlosser loopt!" )
export SCRIPTMAKIRRMKITCHEN=$( echo "Verwijderen vanKitchen" )
export SCRIPTMAKIRSETUPKITCHEN=$( echo "Opzetten van Kitchen" )
export SCRIPTMAKIRDESTROYER=$( echo "Vernietiger loopt!" )
export SCRIPTMAKIRDESTROYEROFWORLDS=$( echo "Vernietiger van werelden loopt!" )
export SCRIPTMAKIRRMREPO=$( echo "Verwijderen van Repository map" )

## Kitchen
export KITCHENMAINMENU=$( echo "Hoofd Menu:" )
export KITCHENMENU1=$( echo "Set-up/Up-date Kitchen" )
export KITCHENMENU2=$( echo "Configureren van Kitchen" )
export KITCHENMENU3=$( echo "Start Kitchen" )
export KITCHENMENU4=$( echo "Herstel Kitchen" )
export KITCHENMENU5=$( echo "Auto Bouw Kitchen" )
export KITCHENMENU6=$( echo "Exit" )
export KITCHENMENUWHICH=$( echo "Welke zou je willen doen?" )
export KITCHENTHANKS=$( echo "Bedankt voor het gebruiken van Swordrune10's Kitchen! Tot ziens.." )
export KITCHENBORED=$( echo "Je lijkt verveeld.. wil je een filmpje kijken?" )
export KITCHENTOUGH=$( echo "jammer!" )

## Reposync
# Usage and Flags
export REPOSYNCUSAGE=$( echo "repo -- programma voor het initialiseren/updaten van android repos" )
export REPOSYNCFLAGD=$( echo "verwijder de gepaste map en verlaat het programma" )
export REPOSYNCFLAGH=$( echo "toon deze help tekst" )
export REPOSYNCFLAGP=$( echo "map leegmaken, herstarten, en dan updaten" )
export REPOSYNCFLAGU=$( echo "update deze particuliere repo" )
export REPOSYNCUPDATE1=$( echo "Update $REPOSKITCHEN" )
export REPOSYNCUPDATE2=$( echo "Update $REPOSAOKP" )
export REPOSYNCUPDATE3=$( echo "Update $REPOSAOSP43" )
export REPOSYNCUPDATE4=$( echo "Update $REPOSAOSP" )
export REPOSYNCUPDATE5=$( echo "Update $REPOSCARBON" )
export REPOSYNCUPDATE6=$( echo "Update $REPOSCM10" )
export REPOSYNCUPDATE7=$( echo "Update $REPOSCM" )
export REPOSYNCUPDATE8=$( echo "Update $REPOSEV" )
export REPOSYNCUPDATE9=$( echo "Update $REPOSOMNI" )
export REPOSYNCUPDATE10=$( echo "Update $REPOSPACMAN" )
export REPOSYNCUPDATE11=$( echo "Update $REPOSPARA" )
export REPOSYNCUPDATE12=$( echo "Update all available repos" )
export REPOSYNCUPDATE13=$( echo "Update all the repos" )
export REPOSYNCUSAGEEXAMP=$( echo "Voorbeeld: reposync -u cm-10.2" )
export REPOSYNCUSAGELIST1=$( echo "typen van \"reposync -u list\" zal" )
export REPOSYNCUSAGELIST2=$( echo "je de opties lijst opnieuw geven" )

# Menu
export REPOSYNCMENUWHAT=$( echo "Wat zijn we aan het updaten?" )
export REPOSYNCMENUINIT=$( echo "Als repo niet is ge‹nitialiseerd, zal het op update zijn" )
export REPOSYNCMENU1=$( echo "Installeer de repo commando" )
export REPOSYNCMENU2=$( echo "Instellen van de bouw omgeving" )
export REPOSYNCMENU3=$( echo "Updaten van $REPOSKITCHEN repository" )
export REPOSYNCMENU4=$( echo "Updaten van $REPOSAOKP repository" )
export REPOSYNCMENU5=$( echo "Updaten van $REPOSAOSP43 repository" )
export REPOSYNCMENU6=$( echo "Updaten van $REPOSAOSP repository" )
export REPOSYNCMENU7=$( echo "Updaten van $REPOSCARBON repository" )
export REPOSYNCMENU8=$( echo "Updaten van $REPOSCM10 repository" )
export REPOSYNCMENU9=$( echo "Updaten van $REPOSCM repository" )
export REPOSYNCMENU10=$( echo "Updaten van $REPOSEV repository" )
export REPOSYNCMENU11=$( echo "Updaten van $REPOSOMNI repository" )
export REPOSYNCMENU12=$( echo "Updaten van $REPOSPACMAN repository" )
export REPOSYNCMENU13=$( echo "Updaten van $REPOSPARA repository" )
export REPOSYNCMENU14=$( echo "Updaten van available repositories" )
export REPOSYNCMENU15=$( echo "Update alle  repos!" )
export REPOSYNCMENU16=$( echo "Update/toevoegen andere repo" )

# Sync and Init
export REPOSYNCNOTINITSKIP=$( echo "niet ge‹nitialiseerd, overslaan" )
export REPOSYNCUPDATING=$( echo "Aan het updaten" )
export REPOSYNCBLAHSMANIFEST=$( echo "'s manifest" )
export REPOSYNCNOTINITYET=$( echo "niet ge‹nitialiseerd, nu initialiserende" )
export REPOSYNCNOTINITWANTTO=$( echo "niet ge‹nitialiseerd, wil je het nu initialiseren?" )
export REPOSYNCINIT=$( echo "initialiserende" )
export REPOSYNCNOTINIT=$( echo "ward niet ge‹nitialiseerd" )
export REPOSYNCREPO=$( echo "repository" )
export REPOSYNCREPOALREADY=$( echo "repo commando is reeds ge‹nstalleerd" )
export REPOSYNCREPOINSTALL=$( echo "Installeren van het repo commando" )
export REPOSYNCCOMPLETE=$( echo "Update Compleet!" )

# Otherrepo Sync and Init
export REPOSYNCADDOR=$( echo "Zijn we andere repo aan het updaten of toevoegen?" )
export REPOSYNCOTHERMENU1=$( echo "Voeg toe aan aangepaste repo map" )
export REPOSYNCOTHERMENU2=$( echo "Update alle aangepaste repos" )
export REPOSYNCOTHERREPONAME=$( echo "Wat is de repo's naam?" )
export REPOSYNCOTHERREPOSHORTNAME=$( echo "Wat is een korte naam voor deze repo? Voorbeeld: Android Open Source Project = aosp" )
export REPOSYNCOTHERREPOURL=$( echo "Wat is de url naar de repo's manifest?" )
export REPOSYNCOTHERREPOBRANCH=$( echo "Wat is de branch in de repo's manifest die je wil gebruiken?" )

## Environmentsetup
export ENVIRONMENTSETUPINIT=$( echo "Initialiseren van de bouw omgeving" )
export ENVIRONMENTSETUPOS=$( echo "Controleren welk besturingssysteem je draait..." )
export ENVIRONMENTSETUPINSTALL=$( echo "Installeren van benodigde paketten, geef alstublieft uw paswoord in" )
export ENVIRONMENTSETUPDXCODE=$( echo "Is Xcode ge‹nstalleerd? We raden versie 3.1.4 aan of nieuwer" )
export ENVIRONMENTSETUPDMACPORTS=$( echo "Is MacPorts ge‹nstalleerd?" )

# Platform
export ENVIRONMENTSETUPFEDORA=$( echo "Je draait Fedora of RedHat!" )
export ENVIRONMENTSETUPDEBIAN=$( echo "Je draait Debian!" )
export ENVIRONMENTSETUPULMN=$( echo "Je draait Ubuntu, ofwel 10.04, 10.10, or 11.04!" )
export ENVIRONMENTSETUPUO=$( echo "Je draait Ubuntu 11.10!" )
export ENVIRONMENTSETUPUPQ=$( echo "Je draait Ubuntu 12.04 or 12.10!" )
export ENVIRONMENTSETUPURST=$( echo "Je draait Ubuntu 13.04, 13.10, or 14.04!" )
export ENVIRONMENTSETUPMINT=$( echo "Je draait Linux Mint!" )
export ENVIRONMENTSETUPARCH=$( echo "Je draait Arch Linux!" )
export ENVIRONMENTSETUPDARWIN=$( echo "Je draait Mac OS X!" )

# Java
export ENVIRONMENTSETUPFLEXION=$( echo "Java installeren zal een tijdje duren, om dit legaal te doen zal de Kitchen delen gebruiken van flexion.org oab-java script" )
export ENVIRONMENTSETUPFLEXION1=$( echo " [x] Ophalen Java SE download page" )
export ENVIRONMENTSETUPFLEXION2=$( echo " [x] Ophalen huidige release download page" )
export ENVIRONMENTSETUPFLEXION3=$( echo " [x] Ophalen vorige releases download page" )
export ENVIRONMENTSETUPWEBUPD8=$( echo "Java installeren zal een tijdje duren, om dit legaal te doen zal de Kitchen webupd8's java installer gebruiken" )

## Preupdate
export PREUPDATEAOSP43=$( echo "Updaten $REPOSAOSP43's local_manifests map" )
export PREUPDATEAOSP=$( echo "Updaten $REPOSAOSP's local_manifests map" )
export PREUPDATECM10=$( echo "Updaten $REPOSCM10's local_manifests map" )
export PREUPDATECM=$( echo "Updaten $REPOSCM's local_manifests map" )
export PREUPDATEOMNI=$( echo "Updaten $REPOSOMNI's local_manifests map" )

## Configkitchen
export CONFIGKITCHENMENUTITLE=$( echo "Kitchen Configuratie Menu" )
export CONFIGKITCHENMENU1=$( echo "Bewerk Gitpuller" )
export CONFIGKITCHENMENU2=$( echo "Bewerk Romeditor" )
export CONFIGKITCHENMENU3=$( echo "Creer/Bewerk andere repo lijst" )
export CONFIGKITCHENOTHERREPO=$( echo "Bewerk aangepaste repos bestandslocatie" )
export CONFIGKITCHENOTHERREPONAME=$( echo "Bewerken aangepaste repo's naam" )

## Fixkitchen
export FIXKITCHENSOMETHINGNOT=$( echo "Er is iets dat niet juist werkt? Wat zullen we doen?" )
export FIXKITCHENPURGE=$( echo "Purge = verwijder bestanden, download van origineel" )
export FIXKITCHENDELETE=$( echo "Delete = verwijder het!" )
export FIXKITCHENMENU1=$( echo "Voeg een repo toe aan een bepaalde local_manifests map" )
export FIXKITCHENMENU2=$( echo "Zuiver een bepaalde local_manifests map" )
export FIXKITCHENMENU3=$( echo "Zuiver of Verwijder een bepaalde repository" )
export FIXKITCHENMENU4=$( echo "Zuiver of Verwijder al de repositories" )
export FIXKITCHENMENU5=$( echo "Zuiver of Verwijder de Kitchen app" )
export FIXKITCHENMENU6=$( echo "Verwijder de Kitchen app, en zijn afhankelijkheden" )
export FIXKITCHENMENU7=$( echo "Verwijder de inhoud van uw computer" )
export FIXKITCHENMENU8=$( echo "Verwijder het gehele internet" )
export FIXKITCHENADD=$( echo "Toevoegen van repo aan otherdevices.xml voor" )
export FIXKITCHENPURGE=$( echo "local_manifests map werdt gezuiverd" )
export FIXKITCHENWHICHADD=$( echo "Aan welke repo zou je willen toevoegen?" )
export FIXKITCHENWHICHPURGE=$( echo "Van welke repo zou je de local_manifests map willen zuiveren?" )
export FIXKITCHENWHICHREPO=$( echo "Welke repo zou je willen zuiveren of verwijderen?" )
export FIXKITCHENPURGEDELETE=$( echo "Zuiveren of Verwijderen?" )
export FIXKITCHENPURGEDELETEEXIT=$( echo "Zuiveren = bestanden verwijderen, downloaden van origineel
Verwijderen = Verwijder het!
type exit om terug te keren" )
export FIXKITCHENPURGEDELETEREPO=$( echo "Zuiver of Verwijder alle repositories?" )
export FIXKITCHENPURGEDELETEKITCHEN=$( echo "Zuiver of Verwijder de Kitchen app?" )
export FIXKITCHENREDEEMER=$( echo "Veranderen naar herstel script.." )
export FIXKITCHENDELETEKITCHEN=$( echo "Ben je er zeker van dat je de Kitchen app wilt verwijderen?" )
export FIXKITCHENTYPEYES=$( echo "Je moet \"ja\" intypen om door te gaan" )
export FIXKITCHENTYPEABORT=$( echo "Type om het even wat anders om de operatie af te blazen" )
export FIXKITCHENDESTROYERSWITCH=$( echo "Veranderen naar Vernietiger script" )
export FIXKITCHENDELETEKITCHENALL=$( echo "Ben je er zeker van dat je de Kitchen app en zijn afhankelijkheden wilt verwijderen?" )
export FIXKITCHENNOTDELETEBUILDS=$( echo "Opmerking: de builds mappen worden niet verwijderd" )
export FIXKITCHENDESTROYEROFWORLDSSWITCH=$( echo "Veranderen naar Vernietiger van Werelden script" )
export FIXKITCHENDELETECOMPUTER=$( echo "Ben je het zeker..? Dit zal alles verwijderen op je computer, inclusief gemounte externe opslag en flash drives!!" )
export SUICIDENOTE=$( echo "Ja, verwijder alstublieft alles van mijn computer" )
export FIXKITCHENMUSTTYPEEXACTLY=$( echo "Je moet dit exact intypen \"$SUICIDENOTE\" om door te gaan" )
export FIXKITCHENTYPEPASSY=$( echo "Geef alstublieft jouw paswoord in om alles te vernietigen" )  
export TROLLFACETITLE=$( echo "Trollface's Android Kitchen!" )
export TROLLFACEUNDERLINE=$( echo "============================" )
export FIXKITCHENIBET=$( echo "Oh jongen, Ik durf te wedden dat je wou dat het zo makkelijk was!" )

## Build Common
export BUILDMENUTITLE=$( echo "Lunch Menu van vandaag:" )
export BUILDREPOMENU1=$( echo "$REPOSAOKP repository" )
export BUILDREPOMENU2=$( echo "$REPOSAOSP43 repository" )
export BUILDREPOMENU3=$( echo "$REPOSAOSP repository" )
export BUILDREPOMENU4=$( echo "$REPOSCARBON repository" )
export BUILDREPOMENU5=$( echo "$REPOSCM10 repository" )
export BUILDREPOMENU6=$( echo "$REPOSCM repository" )
export BUILDREPOMENU7=$( echo "$REPOSEV repository" )
export BUILDREPOMENU8=$( echo "$REPOSOMNI repository" )
export BUILDREPOMENU9=$( echo "$REPOSPACMAN repository" )
export BUILDREPOMENU10=$( echo "$REPOSPARA repository" )
export BUILDALLABOVE=$( echo "Bouw alles hierboven!" )
export BUILDREPONOTSETUP=$( echo "De geselecteerde android repository is niet ingesteld!" )
export BUILDDEVICENOTCOMPATIBLE=$( echo "Dit toestel is niet compatibel met deze repository, probeer opnieuw!" )
export BUILDMENURETURN=$( echo "Terugkeren naar Bouw Menu, Druk Enter om door te gaan: " )

## Buildmenu
export BUILDMENU1=$( echo "Bouw Nexus 4" )
export BUILDMENU2=$( echo "Bouw Nexus 5" )
export BUILDMENU3=$( echo "Bouw Nexus 7" )
export BUILDMENU4=$( echo "Bouw Nexus 10" )
export BUILDMENU5=$( echo "Bouw Galaxy Nexus" )
export BUILDMENU6=$( echo "Bouw Nexus S" )
export BUILDMENU7=$( echo "Bouw Xoom Tablet" )
export BUILDMENU8=$( echo "Bouw all above!" )
export BUILDMENU9=$( echo "Bouw other device" )
export BUILDMENU10=$( echo "Bouw met een andere repository" )

## Builddevice
export BUILDDEVICEBEBUILT=$( echo "is geselecteerd om gebouwd te worden!" )
export BUILDDEVICEWHICHREPO=$( echo "Welke android repository zullen we vandaag gebruiken om te bouwen?" )
export BUILDDEVICENEXUS4=$( echo "Bouw $NEXUS4" )
export BUILDDEVICENEXUS5=$( echo "Bouw $NEXUS5" )
export BUILDDEVICEGSMGNEXUS=$( echo "Bouw $GSMGNEXUS" )
export BUILDDEVICESPRGNEXUS=$( echo "Bouw $SPRGNEXUS" )
export BUILDDEVICEVZWGNEXUS=$( echo "Bouw $VZWGNEXUS" )
export BUILDDEVICEGSMNEXUSS=$( echo "Bouw $GSMNEXUSS" )
export BUILDDEVICESPRNEXUSS=$( echo "Bouw $SPRNEXUSS" )
export BUILDDEVICEWIFINEXUS72012=$( echo "Bouw $WIFINEXUS72012" )
export BUILDDEVICEGSMNEXUS72012=$( echo "Bouw $GSMNEXUS72012" )
export BUILDDEVICEALLNEXUS72012=$( echo "Bouw $ALLNEXUS72012" )
export BUILDDEVICEWIFINEXUS72013=$( echo "Bouw $WIFINEXUS72013" )
export BUILDDEVICELTENEXUS72013=$( echo "Bouw $LTENEXUS72013" )
export BUILDDEVICEALLNEXUS72013=$( echo "Bouw $ALLNEXUS72013" )
export BUILDDEVICENEXUS10=$( echo "Bouw $NEXUS10" )
export BUILDDEVICEWIFIXOOM=$( echo "Bouw $WIFIXOOM" )
export BUILDDEVICEVZWXOOM=$( echo "Bouw $VZWXOOM" )

## Buildother
export BUILDOTHERBEBUILT=$( echo "Bouw ander toestel is geselecteerd om gebouwd te worden!" )
export BUILDOTHERTYPEDEVICE=$( echo "Type alstublieft in voor welk toestel je wil bouwen" )
export BUILDOTHERTYPELIST=$( echo "Type in list om alle ondersteunde toestellen te zien" )
export BUILDOTHERTYPEEXIT=$( echo "Type in exit om terug te keren" )
export BUILDOTHERBUILDTITLE=$( echo "Apparaat Lijst" )
export BUILDOTHERBUILDUNDERLINE=$( echo "===========" )
export BUILDOTHERNOTCOMPATIBLE=$( echo "Dit apparaat in niet compatibel met deze repository, toch bouwen?" )
export BUILDOTHERCONTINUE=$( echo "Doorgaan met bouwen" )
export BUILDOTHERNOTVALID=$( echo "Geen geldig antwoord, gaat niet bouwen" )

## Buildotherrepo
export BUILDOTHERREPOEMPTY=$( echo "ander repo bestand is leeg, voeg alstublieft toe aan bestand en probeer opnieuw!" )
export BUILDOTHERREPOBEBUILT=$( echo "Bouw met andere repository is geselecteerd om gebouwd te worden!" )

## Buildandro
export BUILDANDROCLEAN=$( echo "Map opruimen?" )
export BUILDANDROCLEANENTER=$( echo "Heb je nu juist op enter gedrukt zonder zorgen? daarom ga ik nu de map toch opruimen.." )
export BUILDANDROCCACHECONTINUEWITHOUT=$( echo "Doorgaan zonder ccache gebruik; als je ccache wil gebruiken, stel het dan in" )
export BUILDANDROCCACHEFOUND=$( echo "Gevonden ccache map, zal gebruikt worden om te bouwen" )
export BUILDANDROCCACHEDIDNOTDETECT=$( echo "De kitchen heeft de ccache map niet gedecteerd, wil je er nu een maken?" )
export BUILDANDROCCACHEOTHER=$( echo "Als ccache gelocaliseerd is op een andere locatie type in other" )
export BUILDANDROCCACHEHOWBIG=$( echo "Hoe groot wil je de maximum grootte van ccache? voorgestelde grootte is 50 - 100 gigabytes" )
export BUILDANDROCCACHEAMOUNTTYPED=$( echo "Denk eraan dat het ingetypte getal in gigabytes is" )
export BUILDANDROCCACHEREPONOTSUPPORTED=$( echo "Repository ondersteunt ccache niet, gaat door zonder" )
export BUILDANDROCCACHEEXACTLOCATION=$( echo "Wat is de exacte locatie van ccache? Een voorbeeld van een locatie is ~/.ccache" )
export BUILDANDROCCACHENOTFOUND=$( echo "Gespecificeerde locatie werd niet gevonden, gaat door zonder" )
export BUILDANDROREPONOTSUPPORTED=$( echo "Repository niet ondersteund!" )
export BUILDANDROBUILDMESSEDUP=$( echo "Bouw verknoeid!" )
export BUILDANDROMAKETEMP1=$( echo "Tijdelijke map maken voor post-bouwen" )
export BUILDANDROMAKETEMP2=$( echo "reparaties" )
export BUILDANDROUNZIP=$( echo "Unzippen" )
export BUILDANDRORMSTUFF=$( echo "Verwijderen van onnodige herstel map en bestand_contexts van" )
export BUILDANDROADDROM1=$( echo "Toevoegen rom manager items aan" )
export BUILDANDROADDROM2=$( echo "'s build.prop" )
export BUILDANDROZIP=$( echo "Zippen" )
export BUILDANDROSIGN1=$( echo "Signeren" )
export BUILDANDROSIGN2=$( echo "met test keys" )
export BUILDANDROMOVEOLD1=$( echo "Oudere bouw verplaatsen naar" )
export BUILDANDROMOVEOLD2=$( echo "/oud" )
export BUILDANDROCOPY=$( echo "Kopi‰ren naar" )
export BUILDANDROCLEANUP=$( echo "Opruimen van tijdelijke map" )

## Buildautomenu
export BUILDAUTOMENUTITLE=$( echo "Auto Bouwer Menu" )
export BUILDAUTOMENU1=$( echo "Draai Auto Bouwer" )
export BUILDAUTOMENU2=$( echo "Voeg toe aan auto bouw lijst" )
export BUILDAUTOMENU3=$( echo "Wis auto bouw lijst" )
export BUILDAUTOMENU4=$( echo "Inschakelen Auto Bouwers's output" )
export BUILDAUTOMENU5=$( echo "Inschakelen Auto Bouwer's bouw andere repo" )
export BUILDAUTOMENU6=$( echo "Inschakelen Auto Bouwers's slaap functie" )
export BUILDAUTOMENUSETAUTO=$( echo "Welke android repository stellen we in voor auto bouw?" )
export BUILDAUTOMENUMOVEON=$( echo "Klaar met toevoegen van repo's, ga door naar apparaten toevoegen" )
export BUILDAUTOMENUADD1=$( echo "toegevoegd" )
export BUILDAUTOMENUADD2=$( echo "aan auto bouw bestanden" )
export BUILDAUTOMENUTYPEDEVICE=$( echo "Type alstublieft in Welk android toestel we instellen voor auto bouw" )
export BUILDAUTOMENUWANTTOCLEAR=$( echo "Bent je er zeker van dat je auto bouw bestanden wil wissen?" )
export BUILDAUTOMENUCLEARED=$( echo "Auto bouw bestanden gewist" )
export BUILDAUTOMENUNOTCLEARED=$( echo "Auto bouw bestanden onveranderd gelaten" )
export BUILDAUTOMENUOUTPUT=$( echo "Dit zal buildauto in de swordkitchen script map plaatsen" )
export BUILDAUTOMENUSOMEWHERE=$( echo "Als je het niet ergens anders wilt?" )
export BUILDAUTOMENUTYPEOUTPUT=$( echo "Type ja om het ergens anders te plaatsen:" )
export BUILDAUTOMENUTYPEABSOLUTE=$( echo "Type alstublieft het exacte pad waar je de buildoutput.txt wil opslaan" )
export BUILDAUTOMENUOUTPUTSENT=$( echo "Output word gezonden naar" )
export BUILDAUTOMENUOUTPUTCLEAR=$( echo "Output bestand gewist, bouwauto zal nu regelmatig opslaan" )
export BUILDAUTOMENUADDBELOWREPO=$( echo "Voeg onder deze lijn de repo map toe die je wil auto bouwen, andererepo zijn in de andererepo map, maak een lijst van ‚en repo per lijn" )
export BUILDAUTOMENUADDBELOWDEVICE=$( echo "Voeg onder deze lijn de codenaam toe van het apparaat waarvoor je wil auto bouwen, ‚en apparaat per lijn" )
export BUILDAUTOMENUOTHERREPOON=$( echo "Auto Bouwer's bouw andere repo is nu aan!" )
export BUILDAUTOMENUOTHERREPOOFF=$( echo "Auto Bouwers's bouw andere repo is nu uit!" )
export BUILDAUTOMENUCOMPSLEEPTIME1=$( echo "Wil je dat de computer slaapt voor" )
export BUILDAUTOMENUCOMPSLEEPTIME2=$( echo "een bepaald aantal uren of op een bepaald tijdstip ontwaakt?" )
export BUILDAUTOMENUSLEEPMENU1=$( echo "Ontwaken op een bepaalde tijd" )
export BUILDAUTOMENUSLEEPMENU2=$( echo "Een bepaald aantal uren" )
export BUILDAUTOMENUSPECIFIC1=$( echo "Welk tijdstip wil je dat de bouw server ontwaakt de volgende dag?" )
export BUILDAUTOMENUSPECIFIC2=$( echo "24 uurs configuratie, Voorbeeld: voor 2pm zet 14:00, voor 7am zet 07:00" )
export BUILDAUTOMENUHOURS1=$( echo "Hoe lang wil je dat de bouw server slaapt na het bouwen?" )
export BUILDAUTOMENUHOURS2=$( echo "Het ingegeven getal is in uren" )
export BUILDAUTOMENUTYPEPASSY=$( echo "Geef alstublieft uw gebruiker paswoord in, zodat de bouw server kan slapen" )
export BUILDAUTOMENUSLEEPON=$( echo "Auto Bouwers's slaap functie is nu aan!" )
export BUILDAUTOMENUSLEEPOFF=$( echo "Auto Bouwer's slaap functie is ne uit!" )

## Buildauto
export BUILDAUTOPLEASE=( echo "Gebruik alstublieft het auto bouwer configuratie menu" )
export BUILDAUTOBOTH=( echo "Beide Auto Bouwer's repository en apparaat zijn niet ingesteld!" )
export BUILDAUTOREPO=( echo "Auto Bouwer's repository is niet ingesteld!" )
export BUILDAUTODEVICE=( echo "Auto Bouwerr's apparaat is niet ingesteld!" )
export BUILDAUTOWAIT=( echo "Wachten voor tien minuten! dit is geen aftelling.." )
export BUILDAUTOSLEEP=( echo "Slaap..." )
