#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# English

# Common
export KITCHENTITLE=$( echo "Swordrune10's Android Kitchen!" )
export KITCHENUNDERLINE=$( echo "==============================" )
export NOTPROPERSELECTION=$( echo "You did not make a proper selection, try again!" )
export ENTERTOCONTINUE=$( echo "Press Enter to continue: " )
export MAINMENURETURN=$( echo "Returning to Main Menu, Press Enter to continue: " )
export ANSWERYES=$( echo "yes" )
export ANSWERY=$( echo "y" )
export ANSWERNO=$( echo "no" )
export ANSWERN=$( echo "n" )

# Kitchen
export KITCHENMAINMENU=$( echo "Main Menu:" )
export KITCHENMENU1=$( echo "  1. Setup/Update Kitchen" )
export KITCHENMENU2=$( echo "  2. Configure Kitchen" )
export KITCHENMENU3=$( echo "  3. Run Kitchen" )
export KITCHENMENU4=$( echo "  4. Fix Kitchen" )
export KITCHENMENU5=$( echo "  5. Auto Build Kitchen" )
export KITCHENMENU6=$( echo "  6. Exit" )
export KITCHENMENUWHICH=$( echo "Which one would you like to do?" )
export KITCHENTHANKS=$( echo "Thank you for using Swordrune10's Kitchen! Good bye.." )
export KITCHENBORED=$( echo "You seem bored.. wanna watch a movie?" )
export KITCHENTOUGH=$( echo "tough!" )

## Reposync
# Usage and Flags
export REPOSYNCUSAGE=$( echo "repo -- program to initialize/update android repos" )
export REPOSYNCFLAGD=$( echo "delete the appropriate folder and then exit program" )
export REPOSYNCFLAGH=$( echo "show this help text" )
export REPOSYNCFLAGP=$( echo "purge folder, reinit, and then update" )
export REPOSYNCFLAGU=$( echo "update this particular repo" )
export REPOSYNCUPDATE1=$( echo "Update Kitchen" )
export REPOSYNCUPDATE2=$( echo "Update Android Open Kang Project" )
export REPOSYNCUPDATE3=$( echo "Update Android Open Source Project 4.3" )
export REPOSYNCUPDATE4=$( echo "Update Android Open Source Project 4.4" )
export REPOSYNCUPDATE5=$( echo "Update Carbon" )
export REPOSYNCUPDATE6=$( echo "Update Cyanogenmod 10.2" )
export REPOSYNCUPDATE7=$( echo "Update Cyanogenmod 11" )
export REPOSYNCUPDATE8=$( echo "Update Evervolv" )
export REPOSYNCUPDATE9=$( echo "Update omnirom" )
export REPOSYNCUPDATE10=$( echo "Update PAC-man" )
export REPOSYNCUPDATE11=$( echo "Update ParanoidAndroid" )
export REPOSYNCUPDATE12=$( echo "Update all available repos" )
export REPOSYNCUPDATE13=$( echo "Update all the repos" )
export REPOSYNCUSAGEEXAMP=$( echo "Example: reposync -u cm-10.2" )
export REPOSYNCUSAGELIST1=$( echo "typing \"reposync -u list\" will give" )
export REPOSYNCUSAGELIST2=$( echo "you the options list again" )

# Menu

