#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Brazilian Portuguese

## V1.0 Translated by: Doublepranks ##

## Common
export KITCHENTITLE=$( echo "Swordrune10's Android Kitchen!" )
export KITCHENUNDERLINE=$( echo "==============================" )
## NEEDS TRANSLATION! 
export KITCHENMENUWHICH=$( echo "Which one would you like to do?: " )
## NEEDS TRANSLATION! 
export MENUGOBACK=$( echo "Voltar" )
export NOTPROPERSELECTION=$( echo "Comando invalido, tente novamente!" )
export ENTERTOCONTINUE=$( echo "Pressione enter para continuar: " )
export MAINMENURETURN=$( echo "Retornando ao menu principal, pressione enter para continuar: " )
## NEEDS TRANSLATION! 
export ABORTMESSAGE=$( echo "Aborting.." )
## NEEDS TRANSLATION!
export COMPLETEDMESSAGE=$( echo "Concluido!" )
export QUESTIONYESNO=$( echo "sim/nao? " )
export ANSWERYES=$( echo "Sim" )
export ANSWERY=$( echo "s" )
export ANSWERNO=$( echo "Nao" )
export ANSWERN=$( echo "n" )

## Errors
## NEEDS TRANSLATION!
export ERRORCONTACTINFO=$( echo "If you see this in error, please notify me at either xda or rootzwiki
If you prefer email you can reach me at mishana@swordrune10.net
If your also inclined, i have a freenode channel #Swordrune10Kitchen" )
export ENVIRONMENTSETUP32BIT=$( echo "32-bit not supported!
=====================
Build enviroment installation only supports 64-bit Operating Systems" )
export ENVIRONMENTSETUPNOTSUPPORTED=$( echo "Operating System not supported!
===============================
Supported Operating Systems (only 64-bit):
Ubuntu 10.04 - 13.10 (Full Support)
Debian (General Support)
Linux Mint (General Support)
Arch Linux (General Support)
Fedora (General Support)
Mac OS X (Semi-General Support)" )
## NEEDS TRANSLATION!

## Repos
export REPOSKITCHEN=$( echo "Kitchen app" )
export REPOSAOKP=$( echo "Android Open Kang Project" )
export REPOSAOSP43=$( echo "Android Open Source Project 4.3" )
export REPOSAOSP=$( echo "Android Open Source Project 4.4" )
export REPOSCARBON=$( echo "Carbon" )
export REPOSCM10=$( echo "Cyanogenmod 10.2" )
export REPOSCM=$( echo "Cyanogenmod 11" )
export REPOSEV=$( echo "Evervolv" )
export REPOSOMNI=$( echo "omnirom" )
export REPOSPACMAN=$( echo "PAC-man" )
export REPOSPARA=$( echo "ParanoidAndroid" )

## Devices
## NEEDS TRANSLATION!
export NEXUS4=$( echo "GSM Nexus 4" )
export NEXUS5=$( echo "LTE Nexus 5" )
export GSMGNEXUS=$( echo "GSM Galaxy Nexus" )
export SPRGNEXUS=$( echo "Sprint Galaxy Nexus" )
export VZWGNEXUS=$( echo "Verizon Galaxy Nexus" )
export ALLGNEXUS=$( echo "All Galaxy Nexi" )
export GSMNEXUSS=$( echo "GSM Nexus S" )
export SPRNEXUSS=$( echo "Sprint Nexus S 4G" )
export ALLNEXUSS=$( echo "All Nexus S'" )
export WIFINEXUS72012=$( echo "Wifi Nexus 7 (2012) Tablet" )
export GSMNEXUS72012=$( echo "GSM Nexus 7 (2012) Tablet" )
export ALLNEXUS72012=$( echo "All Nexus 7 (2012) Tablets" )
export WIFINEXUS72013=$( echo "Wifi Nexus 7 (2013) Tablet" )
export LTENEXUS72013=$( echo "LTE Nexus 7 (2013) Tablet" )
export ALLNEXUS72013=$( echo "All Nexus 7 (2013) Tablets" )
export ALLNEXUS7=$( echo "All Nexus 7 Tablets" )
export NEXUS10=$( echo "Wifi Nexus 10" )
export WIFIXOOM=$( echo "Wifi Xoom Tablet" )
export VZWXOOM=$( echo "Verizon Xoom Tablet" )
export ALLXOOM=$( echo "All Xoom Tablets" )
export ALLNEXUS=$( echo "All Nexus Devices" )
## NEEDS TRANSLATION!

## Scriptmakir
## NEEDS TRANSLATION!
export SCRIPTMAKIRREDEEMER=$( echo "Redeemer is running!" )
export SCRIPTMAKIRRMKITCHEN=$( echo "Removing Kitchen" )
export SCRIPTMAKIRSETUPKITCHEN=$( echo "Settng Up Kitchen" )
export SCRIPTMAKIRDESTROYER=$( echo "Destroyer is running!" )
export SCRIPTMAKIRDESTROYEROFWORLDS=$( echo "Destroyer of Worlds is running!" )
export SCRIPTMAKIRRMREPO=$( echo "Removing Repository folder" )
## NEEDS TRANSLATION!

## Kitchen
export KITCHENMAINMENU=$( echo "Menu principal:" )
export KITCHENMENU1=$( echo "Abrir novo/Atualizar Kitchen" )
export KITCHENMENU2=$( echo "Configurar Kitchen" )
export KITCHENMENU3=$( echo "Iniciar Kitchen" )
export KITCHENMENU4=$( echo "Reparar Kitchen" )
export KITCHENMENU5=$( echo "Auto criar Kitchen" )
export KITCHENMENU6=$( echo "Sair" )
export KITCHENTHANKS=$( echo "Volte sempre ;-)" )
export KITCHENBORED=$( echo "Voce parece intediado.. quer assistir um filme?" )
export KITCHENTOUGH=$( echo "ops! Tarde demais..." )

## Reposync
# Usage and Flags
export REPOSYNCUSAGE=$( echo "repo -- Usado para iniciar/atualizar um repositorio" )
export REPOSYNCFLAGD=$( echo "deleta o diretorio alvo e encerra o programa" )
export REPOSYNCFLAGH=$( echo "show this help text" )
export REPOSYNCFLAGP=$( echo "purge folder, reinit, and then update" )
export REPOSYNCFLAGU=$( echo "atualiza o repositorio selecionado repo" )
export REPOSYNCUPDATE1=$( echo "Update $REPOSKITCHEN" )
export REPOSYNCUPDATE2=$( echo "Update $REPOSAOKP" )
export REPOSYNCUPDATE3=$( echo "Update $REPOSAOSP43" )
export REPOSYNCUPDATE4=$( echo "Update $REPOSAOSP" )
export REPOSYNCUPDATE5=$( echo "Update $REPOSCARBON" )
export REPOSYNCUPDATE6=$( echo "Update $REPOSCM10" )
export REPOSYNCUPDATE7=$( echo "Update $REPOSCM" )
export REPOSYNCUPDATE8=$( echo "Update $REPOSEV" )
export REPOSYNCUPDATE9=$( echo "Update $REPOSOMNI" )
export REPOSYNCUPDATE10=$( echo "Update $REPOSPACMAN" )
export REPOSYNCUPDATE11=$( echo "Update $REPOSPARA" )
export REPOSYNCUPDATE12=$( echo "Atualiza todos os repositorios disponiveis" )
export REPOSYNCUPDATE13=$( echo "Atualiza todos os repositorios" )
export REPOSYNCUSAGEEXAMP=$( echo "Exemplo: reposync -u cm-10.2" )
export REPOSYNCUSAGELIST1=$( echo "Digitar \"reposync -u list\" mostra" )
export REPOSYNCUSAGELIST2=$( echo "o menu de opção" )

# Menu
export REPOSYNCMENUWHAT=$( echo "O que vamos atualizar?" )
export REPOSYNCMENUINIT=$( echo "repo sera iniciado durante a atualizacao" )
export REPOSYNCMENU1=$( echo "instalar software repo" )
export REPOSYNCMENU2=$( echo "iniciar ambiente de criacao" )
export REPOSYNCMENU3=$( echo "Atualizar $REPOSKITCHEN" )
export REPOSYNCMENU4=$( echo "Atualizar $REPOSAOKP" )
export REPOSYNCMENU5=$( echo "Atualizar $REPOSAOSP43" )
export REPOSYNCMENU6=$( echo "Atualizar $REPOSAOSP" )
export REPOSYNCMENU7=$( echo "Atualizar $REPOSCARBON" )
export REPOSYNCMENU8=$( echo "Atualizar $REPOSCM10" )
export REPOSYNCMENU9=$( echo "Atualizar $REPOSCM" )
export REPOSYNCMENU10=$( echo "Atualizar $REPOSEV" )
export REPOSYNCMENU11=$( echo "Atualizar $REPOSOMNI" )
export REPOSYNCMENU12=$( echo "Atualizar $REPOSPACMAN" )
export REPOSYNCMENU13=$( echo "Atualizar $REPOSPARA" )
export REPOSYNCMENU14=$( echo "Atualizar repositorios disponiveis" )
export REPOSYNCMENU15=$( echo "Atualizar todos!" )
export REPOSYNCMENU16=$( echo "Atualizar/adicionar outro" )

# Sync and Init
export REPOSYNCNOTINITSKIP=$( echo "Nao iciado, ignorando" )
export REPOSYNCUPDATING=$( echo "Atualizando" )
export REPOSYNCBLAHSMANIFEST=$( echo "'s manifest" )
export REPOSYNCNOTINITYET=$( echo "Nao inicializado, iniciando" )
export REPOSYNCNOTINITWANTTO=$( echo "Nao inicializado, iniciar?" )
export REPOSYNCINIT=$( echo "inicializando" )
export REPOSYNCNOTINIT=$( echo "Nao estava inicializado" )
export REPOSYNCREPO=$( echo "repositorio" )
export REPOSYNCREPOALREADY=$( echo "software repo ja existente" )
export REPOSYNCREPOINSTALL=$( echo "instalando o software repo" )
export REPOSYNCCOMPLETE=$( echo "Atualizacao concluida!" )

# Otherrepo Sync and Init
export REPOSYNCADDOR=$( echo "Adicionar/atualizar outro repositorio?" )
export REPOSYNCOTHERMENU1=$( echo "Adicionar a um diretorio pessoal" )
export REPOSYNCOTHERMENU2=$( echo "Atualizar todos os repositorios pessoais" )
export REPOSYNCOTHERREPONAME=$( echo "Qual o nome do repositorio?" )
export REPOSYNCOTHERREPOSHORTNAME=$( echo "Adicione um codenome ao repositorio? Exemplo: Android Open Source Project = aosp" )
export REPOSYNCOTHERREPOURL=$( echo "URL do arquivo manifest?" )
export REPOSYNCOTHERREPOBRANCH=$( echo "A qual branch o repositorio deve ser atrelado?" )

## EVERYTHING BELOW NEEDS TRANSLATION!

## Environmentsetup
export ENVIRONMENTSETUPINIT=$( echo "Initilizing the build environment" )
export ENVIRONMENTSETUPOS=$( echo "Checking what Operating System you are running.." )
export ENVIRONMENTSETUPINSTALL=$( echo "Installing packages needed, please enter your password" )
export ENVIRONMENTSETUPDXCODE=$( echo "Is Xcode installed? We recommend version 3.1.4 or newer" )
export ENVIRONMENTSETUPDMACPORTS=$( echo "Is MacPorts installed?" )

# Platform
export ENVIRONMENTSETUPFEDORA=$( echo "You are running Fedora or RedHat!" )
export ENVIRONMENTSETUPDEBIAN=$( echo "You are running Debian!" )
export ENVIRONMENTSETUPULMN=$( echo "You are running Ubuntu, either 10.04, 10.10, or 11.04!" )
export ENVIRONMENTSETUPUO=$( echo "You are running Ubuntu 11.10!" )
export ENVIRONMENTSETUPUPQ=$( echo "You are running Ubuntu 12.04 or 12.10!" )
export ENVIRONMENTSETUPURS=$( echo "You are running Ubuntu 13.04 or 13.10!" )
export ENVIRONMENTSETUPMINT=$( echo "You are running Linux Mint!" )
export ENVIRONMENTSETUPARCH=$( echo "You are running Arch Linux!" )
export ENVIRONMENTSETUPDARWIN=$( echo "You are running Mac OS X!" )

# Java
export ENVIRONMENTSETUPFLEXION=$( echo "Installing java will take a while, to do this legally the Kitchen app will use exerpts from flexion.org oab-java script" )
export ENVIRONMENTSETUPFLEXION1=$( echo " [x] Getting Java SE download page" )
export ENVIRONMENTSETUPFLEXION2=$( echo " [x] Getting current release download page" )
export ENVIRONMENTSETUPFLEXION3=$( echo " [x] Getting previous releases download page" )
export ENVIRONMENTSETUPWEBUPD8=$( echo "Installing java will take a while, to do this legally the Kitchen app will use webupd8's java installer" )

## Preupdate
export PREUPDATEAOSP43=$( echo "Updating $REPOSAOSP43's local_manifests folder" )
export PREUPDATEAOSP=$( echo "Updating $REPOSAOSP's local_manifests folder" )
export PREUPDATECM10=$( echo "Updating $REPOSCM10's local_manifests folder" )
export PREUPDATECM=$( echo "Updating $REPOSCM's local_manifests folder" )
export PREUPDATEOMNI=$( echo "Updating $REPOSOMNI's local_manifests folder" )

## Configkitchen
export CONFIGKITCHENMENUTITLE=$( echo "Kitchen Config Menu" )
export CONFIGKITCHENMENU1=$( echo "Edit Gitpuller" )
export CONFIGKITCHENMENU2=$( echo "Edit Romeditor" )
export CONFIGKITCHENMENU3=$( echo "Create/Edit other repo list" )
export CONFIGKITCHENOTHERREPO=$( echo "editing custom repos file location" )
export CONFIGKITCHENOTHERREPONAME=$( echo "editing custom repos name" )

## Build Common
export BUILDMENUTITLE=$( echo "Today's Lunch Menu:" )
export BUILDREPOMENU1=$( echo "$REPOSAOKP repository" )
export BUILDREPOMENU2=$( echo "$REPOSAOSP43 repository" )
export BUILDREPOMENU3=$( echo "$REPOSAOSP repository" )
export BUILDREPOMENU4=$( echo "$REPOSCARBON repository" )
export BUILDREPOMENU5=$( echo "$REPOSCM10 repository" )
export BUILDREPOMENU6=$( echo "$REPOSCM repository" )
export BUILDREPOMENU7=$( echo "$REPOSEV repository" )
export BUILDREPOMENU8=$( echo "$REPOSOMNI repository" )
export BUILDREPOMENU9=$( echo "$REPOSPACMAN repository" )
export BUILDREPOMENU10=$( echo "$REPOSPARA repository" )
export BUILDALLABOVE=$( echo "Build all above!" )
export BUILDREPONOTSETUP=$( echo "The selected android repository is not setup!" )
export BUILDDEVICENOTCOMPATIBLE=$( echo "This device is not compatible with this repository, try again!" )
export BUILDMENURETURN=$( echo "Returning to Build Menu, Press Enter to continue: " )

## Buildmenu
export BUILDMENU1=$( echo "Build Nexus 4" )
export BUILDMENU2=$( echo "Build Nexus 5" )
export BUILDMENU3=$( echo "Build Nexus 7" )
export BUILDMENU4=$( echo "Build Nexus 10" )
export BUILDMENU5=$( echo "Build Galaxy Nexus" )
export BUILDMENU6=$( echo "Build Nexus S" )
export BUILDMENU7=$( echo "Build Xoom Tablet" )
export BUILDMENU8=$( echo "Build all above!" )
export BUILDMENU9=$( echo "Build other device" )
export BUILDMENU10=$( echo "Build with other repository" )

## Builddevice
export BUILDDEVICEBEBUILT=$( echo "is selected to be built!" )
export BUILDDEVICEWHICHREPO=$( echo "Which android repository are we building from today?" )
export BUILDDEVICENEXUS4=$( echo "Build $NEXUS4" )
export BUILDDEVICENEXUS5=$( echo "Build $NEXUS5" )
export BUILDDEVICEGSMGNEXUS=$( echo "Build $GSMGNEXUS" )
export BUILDDEVICESPRGNEXUS=$( echo "Build $SPRGNEXUS" )
export BUILDDEVICEVZWGNEXUS=$( echo "Build $VZWGNEXUS" )
export BUILDDEVICEGSMNEXUSS=$( echo "Build $GSMNEXUSS" )
export BUILDDEVICESPRNEXUSS=$( echo "Build $SPRNEXUSS" )
export BUILDDEVICEWIFINEXUS72012=$( echo "Build $WIFINEXUS72012" )
export BUILDDEVICEGSMNEXUS72012=$( echo "Build $GSMNEXUS72012" )
export BUILDDEVICEALLNEXUS72012=$( echo "Build $ALLNEXUS72012" )
export BUILDDEVICEWIFINEXUS72013=$( echo "Build $WIFINEXUS72013" )
export BUILDDEVICELTENEXUS72013=$( echo "Build $LTENEXUS72013" )
export BUILDDEVICEALLNEXUS72013=$( echo "Build $ALLNEXUS72013" )
export BUILDDEVICENEXUS10=$( echo "Build $NEXUS10" )
export BUILDDEVICEWIFIXOOM=$( echo "Build $WIFIXOOM" )
export BUILDDEVICEVZWXOOM=$( echo "Build $VZWXOOM" )
