#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Brazilian Portuguese

## THIS WHOLE FILE NEEDS TO BE TRANSLATED, NO CURRENT TRANSLATION YET! ##

# Common
export KITCHENTITLE=$( echo "Swordrune10's Android Kitchen!" )
export KITCHENUNDERLINE=$( echo "==============================" )
export NOTPROPERSELECTION=$( echo "You did not make a proper selection, try again!" )
export ENTERTOCONTINUE=$( echo "Press Enter to continue: " )
export ANSWERYES=$( echo "yes" )
export ANSWERY=$( echo "y" )
export ANSWERNO=$( echo "no" )
export ANSWERN=$( echo "n" )

# Kitchen
export KITCHENMAINMENU=$( echo "Main Menu:" )
export KITCHENMENU1=$( echo "  1. Setup/Update Kitchen" )
export KITCHENMENU2=$( echo "  2. Configure Kitchen" )
export KITCHENMENU3=$( echo "  3. Run Kitchen" )
export KITCHENMENU4=$( echo "  4. Fix Kitchen" )
export KITCHENMENU5=$( echo "  5. Auto Build Kitchen" )
export KITCHENMENU6=$( echo "  6. Exit" )
export KITCHENMENUWHICH=$( echo "Which one would you like to do?" )
export KITCHENTHANKS=$( echo "Thank you for using Swordrune10's Kitchen! Good bye.." )
export KITCHENBORED=$( echo "You seem bored.. wanna watch a movie?" )
export KITCHENTOUGH=$( echo "tough!" )
