#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# German

# Common
export KITCHENTITLE=$( echo "Swordrune10 Android Kitchen!" )
export KITCHENUNDERLINE=$( echo "===========================" )
export NOTPROPERSELECTION=$( echo "Sie haben keine gültige Option gewählt, versuchen Sie es erneut!" )
export ENTERTOCONTINUE=$( echo "Drücken Sie die Eingabetaste, um fortzufahren: " )
export ANSWERYES=$( echo "ja" )
export ANSWERY=$( echo "j" )
export ANSWERNO=$( echo "nein" )
export ANSWERN=$( echo "n" )

# Kitchen
export KITCHENMAINMENU=$( echo "Hauptmenü:" )
export KITCHENMENU1=$( echo "  1. Kitchen Einrichten / aktualisieren" )
export KITCHENMENU2=$( echo "  2. Kitchen Konfigurieren" )
export KITCHENMENU3=$( echo "  3. Starten" )
export KITCHENMENU4=$( echo "  4. Kitchen reparieren" )
export KITCHENMENU5=$( echo "  5. Autobuild" )
export KITCHENMENU6=$( echo "  6. Ausgang" )
export KITCHENMENUWHICH=$( echo "Was möchten Sie tun?" )
export KITCHENTHANKS=$( echo "Wir danken für die Nutzung des Swordrune10 Kitchen! Auf Wiedersehen.." )
export KITCHENBORED=$( echo "Sie scheinen gelangweilt .. möchten Sie einen Film schauen?" )
export KITCHENTOUGH=$( echo "super!" )
