#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. ./retardedbabelfish

if ( ! uname -a | grep -q x86_64 ); then
	if ( uname -a | grep -q powerpc ); then
		clear

		echo $BOUNCERPOWERPC
		echo ""
		echo $ERRORSIDEEFFECTS
		echo ""
		echo $ERRORCONTACTINFO
		read -p "$ENTERTOCONTINUE" done
	else
		clear

		echo $BOUNCER32BIT
		echo ""
		echo $ERRORSIDEEFFECTS
		echo ""
		echo $ERRORCONTACTINFO
		read -p "$ENTERTOCONTINUE" done
	fi
fi

homecheck=$( cd $(dirname $0) && cd ../.. && pwd )

if [ $homecheck == $HOME ]; then
	clear

	echo $BOUNCERKITCHENHOME
	echo ""
	echo $ERRORCONTACTINFO
	read -p "$ENTERTOEXIT" done
	kill 0
fi
