#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ( ! uname -a | grep -q x86_64 ); then
	if ( uname -a | grep -q powerpc ); then
		clear

		echo "powerpc processor detected!"
		echo "==================="
		echo "Running powerpc isn't necessarily prohibited, but it is not suggested"
		echo ""
		echo "Side effects may include failure to build properly and lack of support"
		echo "for build environment setup"
		echo ""
		echo "If you see this in error, please notify me at either xda or rootzwiki"
		echo "if you prefer email you can reach me at mishana@swordrune10.net"
		echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
		echo "Press enter to continue.."
		read done
	else
		clear

		echo "32-bit OS detected!"
		echo "==================="
		echo "Running 32-bit isn't necessarily prohibited, but it is not suggested"
		echo ""
		echo "Side effects may include failure to build properly and lack of support"
		echo "for build environment setup"
		echo ""
		echo "If you see this in error, please notify me at either xda or rootzwiki"
		echo "if you prefer email you can reach me at mishana@swordrune10.net"
		echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
		echo "Press enter to continue.."
		read done
	fi
fi

homecheck=$( cd ../../$(dirname $0) && pwd )

if [ $homecheck == $HOME ]; then
	clear

	echo "Kitchen not set in correct place!"
	echo "================================="
	echo "Kitchen will not work correctly if placed in home folder, please move"
	echo ""
	echo "If you see this in error, please notify me at either xda or rootzwiki"
	echo "if you prefer email you can reach me at mishana@swordrune10.net"
	echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
	echo "Press enter to exit.."
	read done
	kill 0
fi
