#!/bin/sh
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd $(dirname $( readlink -f $0 ) )
if ( find .scripts 2> /dev/null 1>&2 ); then
	cd .scripts/utility
	./bouncer

	if ( uname -a | grep -q Darwin ); then
		./macosxinit
	fi
else
	. .scripts/utility/retardedbabelfish
	clear

	echo $ERRORHEADER
	echo $ERRORCONTACTINFO
	read -p "$ENTERTOEXIT" done
	exit 0
fi

export START=true
./headerfile
