#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "kitchen")
	./headerfile
	exit 0
fi

menu () {
clear

echo $KITCHENTITLE
echo $KITCHENUNDERLINE
echo $KITCHENMAINMENU
echo "  1. $KITCHENMENU1"
echo "  2. $KITCHENMENU2"
echo "  3. $KITCHENMENU3"
echo "  4. $KITCHENMENU4"
echo "  5. $KITCHENMENU5"
echo "  6. $KITCHENMENU6"
echo ""
read -p "$KITCHENMENUWHICH" answer

if [ ! "$answer" ] || ( echo $answer | grep -q [A-Za-z] ) || [ $answer -gt "10" ]; then
	echo ""
	echo $NOTPROPERSELECTION
	read -p "$ENTERTOCONTINUE" done
	menu
fi

if [ $answer == "1" ]; then
	reposync
fi

if [ $answer == "2" ]; then
	configkitchen
fi

if [ $answer == "3" ]; then
	buildmenu
fi

if [ $answer == "4" ]; then
	fixkitchen
fi

if [ $answer == "5" ]; then
	buildautomenu
fi

if [ $answer == "6" ]; then
	echo ""
	echo $KITCHENTHANKS
	exit 0
fi

if [ $answer == "7" ] ||[ $answer == "8" ] || [ $answer == "9" ]; then
	echo ""
	echo $NOTPROPERSELECTION
	read -p "$ENTERTOCONTINUE" done
	menu
fi

if [ $answer == "10" ]; then
	echo ""
	echo $KITCHENBORED
	read nothing
	if [ ! "$nothing" ] ||[ $nothing == $ANSWERNO ] || [ $nothing == $ANSWERN ]; then
		echo $KITCHENTOUGH
		read -p "$ENTERTOCONTINUE" done
	fi
	telnet towel.blinkenlights.nl
fi
menu
}
menu
