#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

clear

export POSIXLY_CORRECT=1

echo $MACOSXINITRUN

xinit() {
if ( ! find ~/android.dmg &> /dev/null ); then
	echo ""
	echo $MACOSXINITCANTFINDDMG
	read -p "$QUESTIONYESNO" diskimage

	if [ ! "$diskimage" ]; then
		echo ""
		echo $NOTPROPERSELECTION
		read -p "$ENTERTOCONTINUE" done

		xinit
		exit 0
	elif [ $diskimage == $ANSWERNO ] || [ $diskimage == $ANSWERN ]; then
		echo ""
		echo $ABORTMESSAGE
		read -p "$ENTERTOEXIT" done

		kill 0
	fi


	echo ""
	echo $MACOSXINITHOWBIG
	read gigs

	hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size "$gigs"g ~/android.dmg

	echo ""
	echo $MACOSXINITMOUNTNEW
	hdiutil attach ~/android.dmg -mountpoint /Volumes/android

	if ( ! find ~/bin/repo &> /dev/null ); then
		echo ""
		echo $REPOSYNCREPOINSTALL

		if ( ! find ~/bin &> /dev/null ); then
			mkdir ~/bin
		fi

		curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
		chmod a+x ~/bin/repo
	fi

	echo ""
	echo $MACOSXINITMOVEINTO
	cd /Volumes/android
	mkdir -p swordkitchen
	cd swordkitchen

	echo $MACOSXINITSETUP
	~/bin/repo init -u http://github.com/TeamKeyblade/kitchen_manifest.git -b master
	~/bin/repo sync -j4

else
	echo $MACOSXINITFOUNDDMG
	hdiutil attach ~/android.dmg -mountpoint /Volumes/android

	if ( ! find /Volumes/android/swordkitchen &> /dev/null ); then
		echo ""
		echo $MACOSXINITCANTFINDKITCHEN
		read androidvolume

		if [ ! "$androidvolume" ]; then
			echo ""
			echo $NOTPROPERSELECTION
			read -p "$ENTERTOCONTINUE" done
			read done

			xinit
			exit 0
		fi

		if [ $androidvolume == "no" ] || [ $androidvolume == "n" ]; then
			echo ""
			echo $ABORTMESSAGE
			read -p "$ENTERTOEXIT" done

			kill 0
		fi

		if ( ! find ~/bin/repo &> /dev/null ); then
			echo ""
			echo $REPOSYNCREPOINSTALL

			if ( ! find ~/bin &> /dev/null ); then
				mkdir ~/bin
			fi

			curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
			chmod a+x ~/bin/repo
		fi

		echo ""
		echo $MACOSXINITMOVEINTO
		cd /Volumes/android
		mkdir -p swordkitchen
		cd swordkitchen

		echo $MACOSXINITSETUP
		~/bin/repo init -u http://github.com/TeamKeyblade/kitchen_manifest.git -b master
		~/bin/repo sync -j4
	else
		cd /Volumes/android/swordkitchen
	fi
fi
}

if ( ! find /Volumes/android/swordkitchen &> /dev/null )
	xinit
else
	cd /Volumes/android/swordkitchen
fi
