#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $repodefine == "kitchen" ]; then
	export SCRIPT_REPO=$(echo "kitchen")
	export REPO_PLATFORM=$(echo "master")
	repo_branch=$(echo "master")
	repo_name=$(echo $REPOSKITCHEN)
	repo_url=$(echo "http://github.com/TeamKeyblade/kitchen_manifest.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "aokp" ]; then
	export SCRIPT_REPO=$(echo "aokp")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kitkat")
	repo_name=$(echo $REPOSAOKP)
	repo_url=$(echo "http://github.com/AOKP/platform_manifest.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "aosp44" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "android-4.4.4_r1")
	repo_name=$(echo $REPOSAOSP)
	repo_url=$(echo "https://android.googlesource.com/platform/manifest")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "aosp" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	export REPO_PLATFORM=$(echo "lollipop")
	repo_branch=$(echo "android-5.0.0_r2")
	repo_name=$(echo $REPOSAOSP)
	repo_url=$(echo "https://android.googlesource.com/platform/manifest")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "carbon" ]; then
	export SCRIPT_REPO=$(echo "carbon")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kk")
	repo_name=$(echo $REPOSCARBON)
	repo_url=$(echo "http://github.com/CarbonDev/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "cm11" ]; then
	export SCRIPT_REPO=$(echo "cm")
	export REPO_PLATFORM=$(echo "11")
	repo_branch=$(echo "cm-11.0")
	repo_name=$(echo $REPOSCM)
	repo_url=$(echo "http://github.com/CyanogenMod/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "cm" ]; then
	export SCRIPT_REPO=$(echo "cm")
	export REPO_PLATFORM=$(echo "12")
	repo_branch=$(echo "cm-12.0")
	repo_name=$(echo $REPOSCM)
	repo_url=$(echo "http://github.com/CyanogenMod/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "evervolv" ]; then
	export SCRIPT_REPO=$(echo "evervolv")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kitkat")
	repo_name=$(echo $REPOSEV)
	repo_url=$(echo "http://github.com/Evervolv/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "omni" ]; then
	export SCRIPT_REPO=$(echo "omni")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "android-4.4")
	repo_name=$(echo $REPOSOMNI)
	repo_url=$(echo "http://github.com/omnirom/android.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "pacman" ]; then
	export SCRIPT_REPO=$(echo "pacman")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "pac-4.4")
	repo_name=$(echo $REPOSPACMAN)
	repo_url=$(echo "http://github.com/PAC-man/pacman.git")
	manifest_name=$(echo "default.xml")
fi

if [ $repodefine == "paranoid" ]; then
	export SCRIPT_REPO=$(echo "paranoid")
	export REPO_PLATFORM=$(echo "kitkat")
	repo_branch=$(echo "kitkat")
	repo_name=$(echo "$REPOSPARA")
	repo_url=$(echo "http://github.com/AOSPA/manifest.git")
	manifest_name=$(echo "default.xml")
fi
