#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

initlang () {

langselect () {
# English
echo "  1. English"
# Spanish
echo "  2. español"
# French
echo "  3. français"
# German
echo "  4. Deutsch"
# Italian
echo "  5. italiano"
# Japanese
echo "  6. 日本の"
# Korean
echo "  7. 한국의"
echo "  8. None of the above"
read answer

if [ ! "$answer" ] || ( echo $answer | grep -q [A-Za-z] ) || [ $answer -gt "8" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	langselect
fi

# English
if [ $answer == "1" ]; then
	echo "en" > $LOCAL/config/language
	echo ""
	echo "Language saved as English"
	read -p "Press Enter to continue: " done
fi

# Spanish
if [ $answer == "2" ]; then
	echo "es" > $LOCAL/config/language
	echo ""
	echo "Idioma guardado como español"
	read -p "Pulse Intro para continuar: " done
fi

# French
if [ $answer == "3" ]; then
	echo "fr" > $LOCAL/config/language
	echo ""
	echo "Langue enregistré en tant que français"
	read -p "Appuyez sur Entrée pour continuer: " done
fi

# German
if [ $answer == "4" ]; then
	echo "de" > $LOCAL/config/language
	echo ""
	echo "Die Sprache als Deutsch gespeichert"
	read -p "Drücken Sie die Eingabetaste, um fortzufahren: " done
fi
 # Italian
if [ $answer == "5" ]; then
	echo "it" > $LOCAL/config/language
	echo ""
	echo "Lingua salvato come italiano"
	read -p "Premere Invio per continuare: " done
fi

# Japanese
if [ $answer == "6" ]; then
	echo "ja" > $LOCAL/config/language
	echo ""
	echo "日本人として保存言語"
	read -p "Enterキーを押して続行します。 " done
fi

# Korean
if [ $answer == "7" ]; then
	echo "ko" > $LOCAL/config/language
	echo ""
	echo "한국어로 저장 언어"
	read -p "계속하려면 Enter 키를 누르십시오: " done
fi

if [ $answer == "8" ]; then
	clear

	echo "The Language You Want Is Not Supported!"
	echo "======================================="
	echo "Please notify me what language you are looking for at either xda or rootzwiki"
	echo "if you prefer email you can reach me at mishana@swordrune10.net"
	echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
	read -p "Press Enter to exit.." done
	kill 0
fi
}

## Language Manipulator, this will not stay in script
## Uncomment to use
# export LANG="gb_"

# English
if ( echo $LANG | grep -q "en_" ); then
	clear
	echo "We have detected that your system is set to English"
	echo "Is this how you want the rom kitchen to be?"

	read -p "yes/no?" answer

	if [ "$answer" == "yes" ] || [ "$answer" == "y" ]; then
		echo "en" > $LOCAL/config/language
		echo ""
		echo "Language saved as English"
		read -p "Press Enter to continue: " done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "What language do you want to use instead?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
# Spanish
elif ( echo $LANG | grep -q "es_" ); then
	clear
	echo "Hemos detectado que su sistema está configurado para español"
	echo "¿Es así como quieres la cocina rom que sea?"

	echo ""
	echo "## Esto fue traducido usando Google Translate ##"
	echo "## Póngase en contacto conmigo para hacerme saber"
	echo "si se trataba de una buena traducción o no ##"

	read -p "sí/no?" answer

	if [ "$answer" == "sí" ] || [ "$answer" == "si" ] || [ "$answer" == "s" ]; then
		echo "es" > $LOCAL/config/language
		echo "Idioma guardado como español"
		read -p "Pulse Intro para continuar: " done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "¿En qué idioma desea utilizar en su lugar?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
# French
elif ( echo $LANG | grep -q "fr_" ); then
	clear
	echo "Nous avons détecté que votre système est configuré en français"
	echo "Est-ce la façon dont vous voulez la cuisine rom soit?"

	echo ""
	echo "## Cela a été traduit en utilisant Google Translate ##"
	echo "## S'il vous plaît me contacter pour me faire savoir si"
	echo "c'était une bonne traduction ou pas ##"

	read -p "oui/non?" answer

	if [ "$answer" == "oui" ] || [ "$answer" == "o" ]; then
		echo "fr" > $LOCAL/config/language
		echo ""
		echo "Langue enregistré en tant que français"
		read -p "Appuyez sur Entrée pour continuer: " done
	elif [ "$answer" == "non" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "Quelle langue voulez-vous utiliser à la place?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
# German
elif ( echo $LANG | grep -q "de_" ); then
	clear
	echo "Wir haben festgestellt, dass das System auf Deutsch eingestellt ist"
	echo "Ist das, wie Sie wollen, dass die rom Küche zu sein?"

	echo ""
	echo "## Dies wurde mit Hilfe von Google Translate übersetzt ##"
	echo "## Bitte kontaktieren Sie mich, damit ich weiß, ob dies"
	echo "eine gute Übersetzung ist oder nicht ##"

	read -p "ja/nein?" answer

	if [ "$answer" == "ja" ] || [ "$answer" == "j" ]; then
		echo "de" > $LOCAL/config/language
		echo ""
		echo "Die Sprache als Deutsch gespeichert"
		read -p "Drücken Sie die Eingabetaste, um fortzufahren: " done
	elif [ "$answer" == "nein" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "Welche Sprache sprechen Sie stattdessen verwenden?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
# Italian
elif ( echo $LANG | grep -q "it_" ); then
	clear
	echo "Abbiamo rilevato che il sistema è impostato su italiano"
	echo "È questo come si desidera la cucina rom di essere?"

	echo ""
	echo "## Questo è stato tradotto con Google Translate ##"
	echo "## Vi prego di contattarmi per farmi sapere se"
	echo "questa è stata una buona traduzione o no ##"

	read -p "sì/no?" answer

	if [ "$answer" == "sì" ] || [ "$answer" == "si" ] || [ "$answer" == "s" ]; then
		echo "it" > $LOCAL/config/language
		echo ""
		echo "Lingua salvato come italiano"
		read -p "Premere Invio per continuare: " done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "Che lingua che si desidera utilizzare, invece?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
# Japanese
elif ( echo $LANG | grep -q "ja_" ); then
	clear
	echo "私たちは、あなたのシステムが日本語に設定されていることを検出した"
	echo "これは、ROMのキッチンになりたい方法です？"

	echo ""
	echo "## これは、Googleが翻訳使用して翻訳されました ##"
	echo "## これは良い翻訳したかどうか、私に知らせて、私に連絡してください ##"

	read -p "はい/いいえ？" answer

	if [ "$answer" == "はい" ] || [ "$answer" == "h" ]; then
		echo "ja" > $LOCAL/config/language
		echo ""
		echo "日本人として保存言語"
		read -p "Enterキーを押して続行します。 " done
	elif [ "$answer" == "いいえ" ] || [ "$answer" == "ī" ]; then
		echo ""
		echo "あなたが代わりに使用する言語たいですか？"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
# Korean
elif ( echo $LANG | grep -q "ko_" ); then
	clear
	echo "우리는 당신의 시스템이 한국어로 설정되어 있음을 감지 한"
	echo "이것은 당신이 롬 부엌이 원하는 방법인가?"

	echo ""
	echo "## 이것은 구글 번역 사용하여 번역되었다 ##"
	echo "## 이 안 좋은 번역이었다 또는 알려 주시기"
	echo "위하여 저에게 연락하십시오 ##"

	read -p "예/아니오?" answer

	if [ "$answer" == "예" ] || [ "$answer" == "y" ]; then
		echo "ko" > $LOCAL/config/language
		echo ""
		echo "한국어로 저장 언어"
		read -p "계속하려면 Enter 키를 누르십시오: " done
	elif [ "$answer" == "아니오" ] || [ "$answer" == "a" ]; then
		echo ""
		echo "대신 사용하는 언어는 무엇할까요?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
else
	clear
	echo "We could not detect what language your system uses"
	echo "Default setting is english, will this be ok?"
	read -p "yes/no?" answer

	if [ "$answer" == "yes" ] || [ "$answer" == "y" ]; then
		echo "en" > $LOCAL/config/language
		echo ""
		echo "Language saved as English"
		read -p "Press Enter to continue: " done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "What language do you want to use instead?"
		langselect
	else
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
		initlang
	fi
fi

}

if ( ! find $LOCAL/config/language &> /dev/null ); then
	initlang
fi
