#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

initlang () {

langselect () {
# English
echo "  1. English"
# Spanish
echo "  2. español"
# French
echo "  3. français"
# German
echo "  4. Deutsch"
# Brazilian Portuguese
echo "  5. Brazilian Portuguese"
# Italian
echo "  6. italiano"
# Japanese
echo "  7. 日本の"
# Korean
echo "  8. 한국의"
echo "  9. None of the above"
read answer

if [ ! "$answer" ] || ( echo $answer | grep -q [A-Za-z] ) || [ $answer -gt "9" ]; then
	echo ""
	echo $notproperselection
	read -p  $entertocontinue done
	langselect
fi

# English
if [ $answer == "1" ]; then
	echo "en" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

# Spanish
if [ $answer == "2" ]; then
	echo "es" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

# French
if [ $answer == "3" ]; then
	echo "fr" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

# German
if [ $answer == "4" ]; then
	echo "de" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

# Brazilian Portuguese
if [ $answer == "5" ]; then
	echo "ptbr" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

 # Italian
if [ $answer == "6" ]; then
	echo "it" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

# Japanese
if [ $answer == "7" ]; then
	echo "ja" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

# Korean
if [ $answer == "8" ]; then
	echo "ko" > $LOCAL/config/language
	echo ""
	echo $langsaved
	read -p "$entertocontinue" done
fi

if [ $answer == "9" ]; then
	clear

	echo "The Language You Want Is Not Supported!"
	echo "======================================="
	echo "Please notify me what language you are looking for at either xda or rootzwiki"
	echo "if you prefer email you can reach me at mishana@swordrune10.net"
	echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
	read -p "Press Enter to exit.." done
	kill 0
fi
}

# English
if ( echo $LANG | grep -q "en_" ); then
	langsaved=$( echo "Language saved as English" )
	notproperselection=$( echo "You did not make a proper selection, try again!" )
	entertocontinue=$( echo "Press Enter to continue: " )

	clear
	echo "We have detected that your system is set to English"
	echo "Is this how you want the rom kitchen to be?"

	read -p "yes/no?" answer

	if [ "$answer" == "yes" ] || [ "$answer" == "y" ]; then
		echo "en" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "What language do you want to use instead?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
# Spanish
elif ( echo $LANG | grep -q "es_" ); then
	langsaved=$( echo "Idioma guardado como español" )
	notproperselection=$( echo "No hiciste una elección adecuada, vuelve a intentarlo!" )
	entertocontinue=$( echo "Pulse Intro para continuar: " )

	clear
	echo "Hemos detectado que su sistema está configurado para español"
	echo "¿Es así como quieres que sea la Cocina De Rom?"

	read -p "sí/no?" answer

	if [ "$answer" == "sí" ] || [ "$answer" == "si" ] || [ "$answer" == "s" ]; then
		echo "es" > $LOCAL/config/language
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "¿Qué idioma desea utilizar en su lugar?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
# French
## THIS NEEDS TO BE RETRANSLATED, USED GOOGLE TRANSLATE! ##
elif ( echo $LANG | grep -q "fr_" ); then
	langsaved=$( echo "Langue enregistré en tant que français" )
	notproperselection=$( echo "Vous n'avez pas fait une sélection, essayez de nouveau!" )
	entertocontinue=$( echo "Appuyez sur Entrée pour continuer: " )

	clear
	echo "Nous avons détecté que votre système est configuré en français"
	echo "Est-ce la façon dont vous voulez la cuisine rom soit?"

	read -p "oui/non?" answer

	if [ "$answer" == "oui" ] || [ "$answer" == "o" ]; then
		echo "fr" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "non" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "Quelle langue voulez-vous utiliser à la place?"
		langselect
	else
		echo ""
		echo $notproperselectioin
		read -p "$entertocontinue" done
		initlang
	fi
# German
elif ( echo $LANG | grep -q "de_" ); then
	langsaved=$( echo "Die Sprache Deutsch wurde gespeichert" )
	notproperselection=$( echo "Sie haben keine gültige Option gewählt, versuchen Sie es erneut!" )
	entertocontinue=$( echo "Drücken Sie die Eingabetaste, um fortzufahren: " )

	clear
	echo "Wir haben festgestellt, dass das System auf Deutsch eingestellt ist"
	echo "Ist das die von Ihnen gewünschte Einstellung für das Kitchen?"

	read -p "ja/nein?" answer

	if [ "$answer" == "ja" ] || [ "$answer" == "j" ]; then
		echo "de" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "nein" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "Welche Sprache möchten Sie stattdessen verwenden?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
# Brazilian Portuguese
## THIS NEEDS TO BE TRANSLATED, NO CURRENT TRANSLATION YET! ##
elif ( echo $LANG | grep -q "pt_BR" ); then
	langsaved=$( echo "Language saved as Brazilian Portuguese" )
	notproperselection=$( echo "You did not make a proper selection, try again!" )
	entertocontinue=$( echo "Press Enter to continue: " )

	clear
	echo "We have detected that your system is set to Brazilian Portuguese"
	echo "Is this how you want the rom kitchen to be?"

	read -p "yes/no?" answer

	if [ "$answer" == "yes" ] || [ "$answer" == "y" ]; then
		echo "ptbr" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "What language do you want to use instead?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
# Italian
## THIS NEEDS TO BE RETRANSLATED, USED GOOGLE TRANSLATE! ##
elif ( echo $LANG | grep -q "it_" ); then
	langsaved=$( echo "Lingua salvato come italiano" )
	notproperselection=$( echo "Non hai fatto una selezione corretta, provare di nuovo!" )
	entertocontinue=$( echo "Premere Invio per continuare: " )

	clear
	echo "Abbiamo rilevato che il sistema è impostato su italiano"
	echo "È questo come si desidera la cucina rom di essere?"

	read -p "sì/no?" answer

	if [ "$answer" == "sì" ] || [ "$answer" == "si" ] || [ "$answer" == "s" ]; then
		echo "it" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "Che lingua che si desidera utilizzare, invece?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
# Japanese
## THIS NEEDS TO BE RETRANSLATED, USED GOOGLE TRANSLATE! ##
elif ( echo $LANG | grep -q "ja_" ); then
	langsaved=$( echo "日本人として保存言語" )
	notproperselection=$( echo "あなたが適切な選択をしなかった、もう一度試してみてください！" )
	entertocontinue=$( echo "Enterキーを押して続行します： " )

	clear
	echo "私たちは、あなたのシステムが日本語に設定されていることを検出した"
	echo "これは、ROMのキッチンになりたい方法です？"

	read -p "はい/いいえ？" answer

	if [ "$answer" == "はい" ] || [ "$answer" == "h" ]; then
		echo "ja" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "いいえ" ] || [ "$answer" == "ī" ]; then
		echo ""
		echo "あなたが代わりに使用する言語たいですか？"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
# Korean
## THIS NEEDS TO BE RETRANSLATED, USED GOOGLE TRANSLATE! ##
elif ( echo $LANG | grep -q "ko_" ); then
	langsaved=$( echo "한국어로 저장 언어" )
	notproperselection=$( echo "당신은 올바른 선택을하지 않았다, 다시 시도하십시오!" )
	entertocontinue=$( echo "계속하려면 Enter 키를 누르십시오: " )

	clear
	echo "우리는 당신의 시스템이 한국어로 설정되어 있음을 감지 한"
	echo "이것은 당신이 롬 부엌이 원하는 방법인가?"

	echo ""
	echo "## 이것은 구글 번역 사용하여 번역되었다 ##"
	echo "## 이 안 좋은 번역이었다 또는 알려 주시기"
	echo "위하여 저에게 연락하십시오 ##"

	read -p "예/아니오?" answer

	if [ "$answer" == "예" ] || [ "$answer" == "y" ]; then
		echo "ko" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "아니오" ] || [ "$answer" == "a" ]; then
		echo ""
		echo "대신 사용하는 언어는 무엇할까요?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
else
	langsaved=$( echo "Language saved as English" )
	notproperselection=$( echo "You did not make a proper selection, try again!" )
	entertocontinue=$( echo "Press Enter to continue: " )

	clear
	echo "We could not detect what language your system uses"
	echo "Default setting is english, will this be ok?"
	read -p "yes/no?" answer

	if [ "$answer" == "yes" ] || [ "$answer" == "y" ]; then
		echo "en" > $LOCAL/config/language
		echo ""
		echo $langsaved
		read -p "$entertocontinue" done
	elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
		echo ""
		echo "What language do you want to use instead?"
		langselect
	else
		echo ""
		echo $notproperselection
		read -p "$entertocontinue" done
		initlang
	fi
fi

}

if [ ! "$INIT" ]; then
	export LOCAL=$( cd $(dirname $0) && cd .. && pwd )
fi

if ( ! find $LOCAL/config/language &> /dev/null ); then
	initlang
fi

# English
if ( cat $LOCAL/config/language | grep -q "en" ); then
	. mahimahi
# Spanish
elif ( cat $LOCAL/config/language | grep -q "es" ); then
	. spanishmackerel
# French
elif ( cat $LOCAL/config/language | grep -q "fr" ); then
	. europeanpilchard
# German
elif ( cat $LOCAL/config/language | grep -q "de" ); then
	. rabbitfish
# Brazilian Portuguese
elif ( cat $LOCAL/config/language | grep -q "ptbr" ); then
	. pirarucu
# Italian
elif ( cat $LOCAL/config/language | grep -q "it" ); then
	. italianbleak
# Japanese
elif ( cat $LOCAL/config/language | grep -q "ja" ); then
	. bluefintuna
# Korean
elif ( cat $LOCAL/config/language | grep -q "ko" ); then
	. koreanlamprey
else
	clear

	echo "An Error Has Occurred!"
	echo "======================"
	echo "If you see this in error, please notify me at either xda or rootzwiki"
	echo "if you prefer email you can reach me at mishana@swordrune10.net"
	echo "if your also inclined, i have a freenode channel #Swordrune10Kitchen"
	read -p "Press Enter to exit.." done
	kill 0
fi
