#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $AUTHOR == "xml" ]; then

rm -rf $LOCAL/xml/* &> /dev/null

cat << EOF > $LOCAL/xml/cm11-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="CyanogenMod/android_kernel_google_msm" path="kernel/google/msm" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_asus_flo" path="device/asus/flo" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_asus_deb" path="device/asus/deb" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_lge_mako" path="device/lge/mako" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_asus_grouper" path="kernel/asus/grouper" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_asus_grouper" path="device/asus/grouper" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_asus_tilapia" path="device/asus/tilapia" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_lge_hammerhead" path="kernel/lge/hammerhead" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_lge_hammerhead" path="device/lge/hammerhead" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_samsung_crespo" path="kernel/samsung/crespo" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_crespo" path="device/samsung/crespo" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_crespo4g" path="device/samsung/crespo4g" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_samsung_manta" path="kernel/samsung/manta" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_manta" path="device/samsung/manta" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_samsung_tuna" path="kernel/samsung/tuna" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_tuna" path="device/samsung/tuna" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_maguro" path="device/samsung/maguro" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_toro" path="device/samsung/toro" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_toroplus" path="device/samsung/toroplus" remote="github" revision="cm-11.0" />

  <project name="TheMuppets/proprietary_vendor_acer" path="vendor/acer" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_akm" path="vendor/akm" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_amazon" path="vendor/amazon" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_audience" path="vendor/audience" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_bn" path="vendor/bn" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_elan" path="vendor/elan" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_google" path="vendor/google" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_hardkernel" path="vendor/hardkernel" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_htc" path="vendor/htc" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_lge" path="vendor/lge" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_oppo" path="vendor/oppo" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_sony" path="vendor/sony" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" revision="cm-11.0" />
</manifest>
EOF

cat << EOF > $LOCAL/xml/cm12-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="CyanogenMod/android_kernel_google_msm" path="kernel/google/msm" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_asus_flo" path="device/asus/flo" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_asus_deb" path="device/asus/deb" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_lge_mako" path="device/lge/mako" remote="github" revision="cm-12.0" />

  <project name="CyanogenMod/android_kernel_asus_grouper" path="kernel/asus/grouper" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_asus_grouper" path="device/asus/grouper" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_asus_tilapia" path="device/asus/tilapia" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_lge_hammerhead" path="kernel/lge/hammerhead" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_lge_hammerhead" path="device/lge/hammerhead" remote="github" revision="cm-12.0" />

  <project name="CyanogenMod/android_kernel_samsung_crespo" path="kernel/samsung/crespo" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_samsung_crespo" path="device/samsung/crespo" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_samsung_crespo4g" path="device/samsung/crespo4g" remote="github" revision="cm-11.0" />

  <project name="CyanogenMod/android_kernel_samsung_manta" path="kernel/samsung/manta" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_samsung_manta" path="device/samsung/manta" remote="github" revision="cm-12.0" />

  <project name="CyanogenMod/android_kernel_samsung_tuna" path="kernel/samsung/tuna" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_samsung_tuna" path="device/samsung/tuna" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_samsung_maguro" path="device/samsung/maguro" remote="github" revision="cm-12.0" />
  <project name="CyanogenMod/android_device_samsung_toro" path="device/samsung/toro" remote="github" revision="cm-11.0" />
  <project name="CyanogenMod/android_device_samsung_toroplus" path="device/samsung/toroplus" remote="github" revision="cm-11.0" />

  <project name="TheMuppets/proprietary_vendor_acer" path="vendor/acer" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_akm" path="vendor/akm" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_amazon" path="vendor/amazon" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_audience" path="vendor/audience" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_bn" path="vendor/bn" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_elan" path="vendor/elan" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_htc" path="vendor/htc" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_lge" path="vendor/lge" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_motorola" path="vendor/motorola" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_oppo" path="vendor/oppo" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_sony" path="vendor/sony" revision="cm-12.0" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" revision="cm-12.0" />
</manifest>
EOF

cat << EOF > $LOCAL/xml/aosp-jb-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="github"
           fetch="http://github.com/" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_audience" path="vendor/audience" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_elan" path="vendor/elan" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_imgtec" path="vendor/imgtec" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_lge" path="vendor/lge" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" remote="github" revision="cm-10.2" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" remote="github" revision="cm-10.2" />
</manifest>
EOF

cat << EOF > $LOCAL/xml/aosp-kitkat-local_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="github"
           fetch="http://github.com/" />
  <project name="TheMuppets/proprietary_vendor_asus" path="vendor/asus" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_audience" path="vendor/audience" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_broadcom" path="vendor/broadcom" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_elan" path="vendor/elan" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_invensense" path="vendor/invensense" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_lge" path="vendor/lge" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_nvidia" path="vendor/nvidia" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_nxp" path="vendor/nxp" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_samsung" path="vendor/samsung" remote="github" revision="cm-11.0" />
  <project name="TheMuppets/proprietary_vendor_widevine" path="vendor/widevine" remote="github" revision="cm-11.0" />
</manifest>
EOF

fi

if [ $AUTHOR == "otherdevicesxml" ]; then

cat << EOF > ./otherdevices.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
</manifest>
EOF

fi

if [ $AUTHOR == "gitpuller" ]; then

cat << EOF > $LOCAL/config/gitpuller
#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ \$SCRIPT_REPO == "aokp" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "aosp" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "cm" ] && [ \$REPO_PLATFORM == "10.2" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "cm" ] && [ \$REPO_PLATFORM == "11" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "evervolv" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "omni" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "pacman" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi

if [ \$SCRIPT_REPO == "paranoid" ]; then
	# below is examples, git pull is recommended
	# cd \$REPOS/cm-ics/where-in-the-repo-you-want-to-modify
	# git pull repo-you-want-to-pull
	exit 0
fi
EOF

chmod a+x $LOCAL/config/gitpuller

fi

if [ $AUTHOR == "romeditor" ]; then

cat << EOF > $LOCAL/config/romeditor
#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ \$SCRIPT_REPO == "cm" ]; then
	cd \$REPOS/cm-\$REPO_PLATFORM/vendor/cm/config
	sed -i 's/developerid=cyanogenmod/developerid=\$(shell whoami)/g' common.mk
	sed -i 's/CM_BUILDTYPE := UNOFFICIAL/CM_BUILDTYPE := SWORDKITCHEN/g' common.mk
	sed -i 's/shell date -u +%Y%m%d/shell date +%Y%m%d/g' common.mk
fi
EOF

chmod a+x $LOCAL/config/romeditor

fi

if [ $AUTHOR == "otherrepo" ]; then

touch $LOCAL/config/otherrepo
touch $LOCAL/config/otherreponame

fi

if [ $AUTHOR == "redeemer" ]; then

cat << EOF > $LOCAL/../redeemer
#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo $SCRIPTMAKIRREDEEMER
echo ""
echo $SCRIPTMAKIRRMKITCHEN
echo ""
rm -rf .repo
rm -rf .scripts
rm -f swordkitchen.sh
echo $SCRIPTMAKIRSETUPKITCHEN
echo ""
repo init -u http://github.com/TeamKeyblade/kitchen_manifest.git -b master
repo sync
echo $COMPLETEDMESSAGE
read -p "$ENTERTOCONTINUE" done
rm -f $LOCAL/../redeemer
EOF

chmod a+x $LOCAL/../redeemer

fi

if [ $AUTHOR == "destroyer" ] || [ $AUTHOR == "destroyerofworlds" ]; then

cat << START > $LOCAL/../$AUTHOR
#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

START

if [ $AUTHOR == "destroyer" ]; then
cat << TITLE >> $LOCAL/../$AUTHOR
echo $SCRIPTMAKIRDESTROYER
TITLE
elif [ $AUTHOR == "destroyerofworlds" ]; then
cat << TITLE >> $LOCAL/../$AUTHOR
echo $SCRIPTMAKIRDESTROYEROFWORLDS
TITLE
fi

cat << BODY >> $LOCAL/../$AUTHOR
echo ""
echo $SCRIPTMAKIRRMKITCHEN
echo ""
rm -rf .repo
rm -rf \$LOCAL
rm -f swordkitchen.sh
BODY

if [ $AUTHOR == "destroyerofworlds" ]; then
cat << DESTROYREPOS >> $LOCAL/../$AUTHOR
echo $SCRIPTMAKIRRMREPO
echo ""
rm -rf \$REPOS
DESTROYREPOS
fi

cat << EOF >> $LOCAL/../$AUTHOR
echo $COMPLETEDMESSAGE
read -p "$ENTERTOCONTINUE" done
rm -f $LOCAL/../$AUTHOR
EOF

chmod a+x $LOCAL/../$AUTHOR

fi
