#!/bin/bash
# Written by Sean Donovan (swordrune10)
if [ $SCRIPT_REPO == "cm" ]; then
	cd $REPOS/cm-$REPO_PLATFORM/vendor/cm
	./get-prebuilts

	#this is rebuilt every time since this file is likely to change alot
	wget -o /dev/null -O $LOCAL/config/cm-master-list \
	https://raw.github.com/CyanogenMod/hudson/master/cm-build-targets
fi

if [ $SCRIPT_REPO == "pacman" ]; then
	cd $REPOS/pacman-$REPO_PLATFORM/vendor/cm
	./get-prebuilts
fi

if [ $SCRIPT_REPO == "raosp" ]; then
	cd $REPOS/raosp-$REPO_PLATFORM/vendor/keyblade/scripts
	./setup-repo
fi
