#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $SCRIPT_REPO == "cm" ]; then
	cd $REPOS/cm-$REPO_PLATFORM/vendor/cm
	./get-prebuilts

	#this is rebuilt every time since this file is likely to change alot
	curl https://raw.github.com/CyanogenMod/hudson/master/cm-build-targets > $LOCAL/config/cm-master-list
fi

if [ $SCRIPT_REPO == "pacman" ]; then
	cd $REPOS/pacman-$REPO_PLATFORM/vendor/cm
	./get-prebuilts
fi
