#!/bin/bash
# Written by Sean Donovan (swordrune10)
if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "ics" ]; then
	cd $REPOS/cm-ics/vendor/cm
	./get-prebuilts
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "jellybean" ]; then
	cd $REPOS/cm-jellybean/vendor/cm
	./get-prebuilts
fi

if [ $SCRIPT_REPO == "rooted-aosp" ]; then
	rm -rf system/extras/su
fi

if [ $SCRIPT_REPO == "sts" ]; then
	cd $REPOS/sts-ics/vendor/cm
	./get-prebuilts
fi

if [ $SCRIPT_REPO == "gummy" ]; then
	cd $REPOS/gummy-ics/vendor/Gummy
	./get-prebuilts
fi
