#!/bin/bash
# Written by Sean Donovan (swordrune10)
localmanifests=$( echo "$REPO_FOLDER/.repo/local_manifests" )

if ( ! find $localmanifests &> /dev/null ); then
	mkdir $localmanifests
fi

if [ $SCRIPT_REPO == "aokp" ]; then
	rm -rf vendor/aokp
	echo ""
	echo "Updating Android Open Kang Project's local_manifests folder"
	wget https://raw.github.com/AOKP/platform_manifest/jb/kernel_manifest.xml -O $localmanifests/kernel_manifest.xml
fi

if [ $SCRIPT_REPO == "aosp" ]; then
	echo ""
	echo "Updating Android Open Source Project's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/aosp-jb-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "cna" ]; then
	rm -rf vendor/cna
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "ics" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 9's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm9-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "jb" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 10's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "10.2" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 10.2's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10.2-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "evervolv" ]; then
	rm -rf vendor/ev
fi

if [ $SCRIPT_REPO == "paranoid" ]; then
	rm -rf vendor/cm
	rm -rf vendor/pa
	echo ""
	echo "Updating ParanoidAndroid's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "raosp" ]; then
	rm -rf vendor/keyblade
	echo ""
	echo "Updating Rooted & Busyboxed's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/raosp-jb-local_manifest.xml $localmanifests/proprietary.xml
fi
