#!/bin/bash
# Written by Sean Donovan (swordrune10)
localmanifests=$( echo "$repo_folder/.repo/local_manifests" )

if ( ! find $localmanifests &> /dev/null ); then
	mkdir $localmanifests
fi

if [ $script_repo == "aokp" ]; then
	rm -rf vendor/aokp
fi

if [ $script_repo == "aosp" ] && [ $repo_platform == "jb" ]; then
	echo ""
	echo "Updating Android Open Source Project's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/aosp-jb-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $script_repo == "aosp" ] && [ $repo_platform == "kitkat" ]; then
	echo ""
	echo "Updating Android Open Source Project's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/aosp-kitkat-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $script_repo == "cna" ]; then
	rm -rf vendor/cna
fi

if [ $script_repo == "cm" ] && [ $repo_platform == "10.2" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 10.2's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10.2-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $script_repo == "cm" ] && [ $repo_platform == "11" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 11's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm11-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $script_repo == "carbon" ]; then
	rm -rf vendor/carbon
fi

if [ $script_repo == "evervolv" ]; then
	rm -rf vendor/ev
fi

if [ $script_repo == "omni" ]; then
	rm -rf vendor/custom
	echo ""
	echo "Updating omnirom's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/aosp-kitkat-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $script_repo == "pacman" ]; then
	rm -rf vendor/cm
	rm -rf vendor/pa
	rm -rf vendor/pac
	echo ""
	echo "Updating PAC-man's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10.2-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $script_repo == "paranoid" ]; then
	rm -rf vendor/pa
fi
