#!/bin/bash
# Written by Sean Donovan (swordrune10)
localmanifests=$( echo "$REPO_FOLDER/.repo/local_manifests" )

if ( ! find $localmanifests &> /dev/null ); then
	mkdir $localmanifests
fi

if [ $SCRIPT_REPO == "aokp" ]; then
	rm -rf vendor/aokp
fi

if [ $SCRIPT_REPO == "aosp" ]; then
	echo ""
	echo "Updating Android Open Source Project's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/aosp-jb-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "cna" ]; then
	rm -rf vendor/cna
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "ics" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 9's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm9-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "jb" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 10's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "cm" ] && [ $REPO_PLATFORM == "10.2" ]; then
	rm -rf vendor/cm
	echo ""
	echo "Updating Cyanogenmod 10.2's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10.2-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "carbon" ]; then
	rm -rf vendor/carbon
fi

if [ $SCRIPT_REPO == "evervolv" ]; then
	rm -rf vendor/ev
fi

if [ $SCRIPT_REPO == "omni" ]; then
	rm -rf vendor/custom
	echo ""
	echo "Updating omnirom's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10.2-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "pacman" ]; then
	rm -rf vendor/cm
	rm -rf vendor/pa
	rm -rf vendor/pac
	echo ""
	echo "Updating PAC-man's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/cm10.2-local_manifest.xml $localmanifests/proprietary.xml
fi

if [ $SCRIPT_REPO == "paranoid" ]; then
	rm -rf vendor/pa
fi

if [ $SCRIPT_REPO == "raosp" ]; then
	rm -rf vendor/keyblade
	echo ""
	echo "Updating Rooted & Busyboxed's local_manifests folder"
	export AUTHOR="xml"
	scriptmakir
	cp -f $LOCAL/xml/raosp-jb-local_manifest.xml $localmanifests/proprietary.xml
	curl https://raw.github.com/TeamKeyblade/android_manifest/raosp/raosp.xml > $localmanifests/raosp.xml
fi
