#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "buildmenu")
	../headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Today's Menu:"
echo "  1. Build Galaxy Nexus"
echo "  2. Build Nexus S"
echo "  3. Build Xoom Tablet"
echo "  4. Build all above!"
echo "  5. Build Droid 3/Droid 4/Bionic/Razr"
echo "  6. Build other device"
echo "  7. Build with other repository"
echo "  8. Go Back"
echo ""
echo "Which one would you like to do?"
read buildanswer

if [ "$buildanswer" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if ( echo $buildanswer | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if [ $buildanswer -gt "8" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if [ $buildanswer == "1" ]; then
	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Today's Menu:"
	echo "  1. Build Verizon Galaxy Nexus"
	echo "  2. Build GSM Galaxy Nexus"
	echo "  3. Build Sprint Galaxy Nexus"
	echo "  4. Build all above!"
	echo "  5. Go Back"
	echo ""
	echo "Which one would you like to do?"
	read buildgnexus

	if [ "$buildgnexus" == "" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if ( echo $buildgnexus | grep -q [A-Za-z] ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if [ $buildgnexus -gt "5" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if [ $buildgnexus == "1" ]; then
		buildtoro
		read done
	fi

	if [ $buildgnexus == "2" ]; then
		buildmaguro
		read done
	fi

	if [ $buildgnexus == "3" ]; then
		buildtoroplus
		read done
	fi

	if [ $buildgnexus == "4" ]; then
		buildgnexus
		read done
	fi
fi

if [ $buildanswer == "2" ]; then
	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Today's Menu:"
	echo "  1. Build GSM Nexus S"
	echo "  2. Build Sprint Nexus S 4G"
	echo "  3. Build all above!"
	echo "  4. Go Back"
	echo ""
	echo "Which one would you like to do?"
	read buildnexuss

	if [ "$buildnexuss" == "" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if ( echo $buildnexuss | grep -q [A-Za-z] ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if [ $buildnexuss -gt "4" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if [ $buildnexuss == "1" ]; then
		buildcrespo
		read done
	fi

	if [ $buildnexuss == "2" ]; then
		buildcrespo4g
		read done
	fi

	if [ $buildnexuss == "3" ]; then
		buildnexuss
		read done
	fi
fi

if [ $buildanswer == "3" ]; then
	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "Today's Menu:"
	echo "  1. Build Verizon Xoom Tablet"
	echo "  2. Build Wifi Xoom Tablet"
	echo "  3. Build all above!"
	echo "  4. Go Back"
	echo ""
	echo "Which one would you like to do?"
	read buildxoom

	if [ "$buildxoom" == "" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if ( echo $buildxoom | grep -q [A-Za-z] ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if [ $buildxoom -gt "4" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
	fi

	if [ $buildxoom == "1" ]; then
		buildstingray
		read done
	fi

	if [ $buildxoom == "2" ]; then
		buildwingray
		read done
	fi

	if [ $buildxoom == "3" ]; then
		buildxoom
		read done
	fi
fi

if [ $buildanswer == "4" ]; then
	buildsts
	read done
fi

if [ $buildanswer == "5" ]; then
	buildsts
	read done
fi

if [ $buildanswer == "6" ]; then
	buildother
	read done
fi

if [ $buildanswer == "7" ]; then
	buildotherrepo
	read done
fi

if [ $buildanswer == "8" ]; then
	echo ""
	echo "Returning to Main Menu, Press Enter to continue"
	read done
	exit 0
fi

menu
}
menu
