#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "buildmenu")
	../headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Today's Menu:"
echo "  1. Build Galaxy Nexus"
echo "  2. Build Nexus S"
echo "  3. Build Xoom Tablet"
echo "  4. Build all above!"
echo "  5. Build Droid 3/Droid 4/Bionic/Razr"
echo "  6. Build other device"
echo "  7. Build with other repository"
echo "  8. Go Back"
echo ""
echo "Which one would you like to do?"
read buildanswer

if [ "$buildanswer" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	menu
fi

if ( echo $buildanswer | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	menu
fi

if [ $buildanswer -gt "8" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	menu
fi

if [ $buildanswer == "1" ]; then
	export builddevicemenu=$(echo "gnexusmenu")
	builddevice
	read done
fi

if [ $buildanswer == "2" ]; then
	export builddevicemenu=$(echo "nexussmenu")
	builddevice
	read done
fi

if [ $buildanswer == "3" ]; then
	export builddevicemenu=$(echo "xoommenu")
	builddevice
	read done
fi

if [ $buildanswer == "4" ]; then
	export builddevicemenu=$(echo "allmenu")
	builddevice
	read done
fi

if [ $buildanswer == "5" ]; then
	buildsts
	read done
fi

if [ $buildanswer == "6" ]; then
	buildother
	read done
fi

if [ $buildanswer == "7" ]; then
	buildotherrepo
	read done
fi

if [ $buildanswer == "8" ]; then
	echo ""
	read -p "Returning to Main Menu, Press Enter to continue: " done
	exit 0
fi

menu
}
menu
