#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "configkitchen")
	../headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we setting up?"
echo "  1. Edit Gitpuller"
echo "  2. Edit Romeditor"
echo "  3. Add a different repo"
echo "  4. Auto Builder Config"
echo "  5. Go Back"
echo ""
echo "Which one would you like to do?"
read configs

if [ "$configs" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if ( echo $configs | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if [ $configs -gt "5" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if [ $configs == "1" ]; then
	cd $LOCAL/config
	nano gitpuller
fi

if [ $configs == "2" ]; then
	cd $LOCAL/config
	nano romeditor
fi

if [ $configs == "3" ]; then
	cd $LOCAL/config
	if [ "$(cat otherrepo)" == "" ]; then
		echo "# Add below this line the absolute path to the desired repo" > otherrepo
	else
		sed -i -e "0,/.*/ i \
# Add below this line the absolute path to the desired repo" \
		otherrepo
	fi

	nano otherrepo
	sed -i "/# /d" otherrepo
fi

if [ $configs == "4" ]; then

buildauto(){
	clear

	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "What are we setting up?"
	echo "  1. List all available repository tags for Auto Builder"
	echo "  2. Edit what repositories Auto Builder uses"
	echo "  3. Edit what devices Auto Builder builds"
	echo "  4. Edit where Auto Builder's output goes"
	echo "  5. Toggle Auto Builder's sleep function"
	echo "  6. Go Back"
	echo ""
	echo "Which one would you like to do?"
	read buildautoconfig

	if [ "$buildautoconfig" == "" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
		buildauto
	fi

	if ( echo $buildautoconfig | grep -q [A-Za-z] ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
		buildauto
	fi

	if [ $buildautoconfig -gt "6" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read done
		buildauto
	fi

	if [ $buildautoconfig == "1" ]; then
		cat $LOCAL/repolist | less
	fi

	if [ $buildautoconfig == "2" ]; then
		cd $LOCAL/config
		if [ "$(cat scriptrepo)" == "" ]; then
			echo "# Add below this line the repo tag you want to auto build, list each repo per line" > scriptrepo
		else
			sed -i -e "0,/.*/ i \
# Add below this line the repo tag you want to auto build, list each repo per line" \
			scriptrepo
		fi

		nano scriptrepo
		sed -i "/# /d" scriptrepo
	fi

	if [ $buildautoconfig == "3" ]; then
		cd $LOCAL/config
		if [ "$(cat scriptdevice)" == "" ]; then
			echo "# Add below this line the device codename you want to auto build, list each device per line" > scriptdevice
		else
			sed -i -e "0,/.*/ i \
# Add below this line the device codename you want to auto build, list each device per line" \
			scriptdevice
		fi

		nano scriptdevice
		sed -i "/# /d" scriptdevice
	fi

	if [ $buildautoconfig == "4" ]; then
		cd $LOCAL/config
		echo "Please type the absolute path of where u want the buildoutput.txt to be"
		read sleeptime

		echo $outfilelocation > outfile
	fi

	if [ $buildautoconfig == "5" ]; then
		if ( ! find $LOCAL/config/sleepybuildserver ); then
			cd $LOCAL/config
			echo "How long would you like for the build server to sleep after building?"
			echo "The number being inputted is in hours"
			read sleeptime

			echo $sleeptime > sleepybuildserver

			echo "Please type in your user's password, so the build server can sleep"
			while true; do
				read -p "$star" -r -s -n 1 letter
				star="*"

				if [ "$letter" == "" ]; then
					break
				fi

				passy=$passy$letter
			done

			echo
			echo $passy >> sleepybuildserver

			echo "Auto Builder's sleep function is now on!"
			read done
		else
			rm -f $LOCAL/config/sleepybuildserver
			echo "Auto Builder's sleep function is now off!"
			read done
		fi

	fi

	if [ $buildautoconfig == "6" ]; then
		echo ""
		echo "Press Enter to go back"
		read done
		menu
	fi
buildauto
}
buildauto
fi

if [ $configs == "5" ]; then
	echo ""
	echo "Returning to Main Menu, Press Enter to continue"
	read done
	exit 0
fi

menu
}
menu
