#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "configkitchen")
	../headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "Kitchen Config Menu"
echo "  1. Edit Gitpuller"
echo "  2. Edit Romeditor"
echo "  3. Create/Edit other repo list"
echo "  4. Go Back"
echo ""
read -p "Which one would you like to do?: " configs

if [ "$configs" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	menu
fi

if ( echo $configs | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	menu
fi

if [ $configs -gt "4" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
	menu
fi

if [ $configs == "1" ]; then
	cd $LOCAL/config
	nano gitpuller
fi

if [ $configs == "2" ]; then
	cd $LOCAL/config
	nano romeditor
fi

if [ $configs == "3" ]; then
	cd $LOCAL/config
	if [ "$(cat otherrepo)" == "" ]; then
		echo "# Add below this line the absolute path to the desired repo" > otherrepo
	else
		sed -i -e "0,/.*/ i \
# Add below this line the absolute path to the desired repo" \
		otherrepo
	fi

	nano otherrepo
	sed -i "/# /d" otherrepo
fi

if [ $configs == "4" ]; then
	echo ""
	read -p "Returning to Main Menu, Press Enter to continue: " done
	exit 0
fi

menu
}
menu
