#!/bin/bash
# Written by Sean Donovan (swordrune10)

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we setting up?"
echo "  1. Edit Gitpuller"
echo "  2. Edit Romeditor"
echo "  3. Add a different repo"
echo "  4. Go Back"
echo ""
echo "Which one would you like to do?"
read configs

if [ "$configs" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if ( echo $configs | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if [ $configs -gt "4" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	echo "Press Enter to continue"
	read done
	menu
fi

if [ $configs == "1" ]; then
	cd $LOCAL/config
	nano gitpuller
fi

if [ $configs == "2" ]; then
	cd $LOCAL/config
	nano romeditor
fi

if [ $configs == "3" ]; then
	cd $LOCAL/config
	sed -i -e " i \
# Add below the path to desired repo, absolute path recommended" \
	otherrepo
	nano otherrepo
	sed -i "/# /d" otherrepo
fi

if [ $configs == "4" ]; then
	echo ""
	echo "Returning to Main Menu, Press Enter to continue"
	read done
	exit 0
fi

echo ""
echo "Press Enter to continue"
read done
}
menu
