#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "reposetup")
	../headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we setting up?"
echo "  1. Install the repo command"
echo "  2. initialize the build enviroment"
echo "  3. initialize the Kitchen app repository"
echo "  4. initialize the Android Open Kang Project repository"
echo "  5. initialize the Android Open Source Project repository"
echo "  6. initialize the Cyanogenmod 9 repository"
echo "  7. initialize the Evervolv repository"
echo "  8. initialize the Rooted & Busyboxed AOSP repository"
echo "  9. initialize the Solana/Targa/Spyder Dev Team repository"
echo "  10. initialize the Team Gummy repository"
echo "  11. Go Back"
echo ""
echo "Which one would you like to do?"
read setupanswer

if [ ! "$setupanswer" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if ( echo $setupanswer | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer -gt "11" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "1" ]; then
	if ( type -a repo &> /dev/null ); then
		echo ""
		echo "repo is already installed.."
	else
		echo ""
		echo "Installing the repo command.."

		if ( ! find ~/bin &> /dev/null ); then
			mkdir ~/bin
		fi

		wget https://dl-ssl.google.com/dl/googlesource/git-repo/repo -O ~/bin/repo
		chmod a+x ~/bin/repo

		echo ""
		echo "Finished!"
		read -p "Press Enter to continue: " done
	fi
fi

if [ $setupanswer == "2" ]; then
	environmentsetup
fi

setupcode() {
if [ ! "$kitchensync" ]; then
	repo_folder=$( echo "$REPOS/$script_repo-$repo_platform" )
fi

if ( ! find $repo_folder/.repo &> /dev/null ); then
	echo "initializing $repo_name repository.."

	if [ ! "$kitchensync" ]; then
		mkdir -p $repo_folder
	fi

	cd $repo_folder

	repo init -u $repo_url -b $repo_platform

	echo ""
	echo "Sync $repo_name repository?"
	read -p "yes/no? " newreposync

	if [ "$newreposync" == "yes" ] || [ "$newreposync" == "y" ]; then
		INIT=""
		reposync $script_repo
	fi

	if [ ! "$newreposync" ] || [ "$newreposync" == "no" ] || [ "$newreposync" == "n" ]; then
		echo ""
		echo "$repo_name repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
else
	echo "$repo_name already initialized.."
	read -p "Press Enter to continue: " done
fi
}

if [ $setupanswer == "3" ]; then
	kitchensync=true
	script_repo=$(echo "kitchen")
	repo_platform=$(echo "stable")
	repo_folder=$( echo "$LOCAL/.." )
	repo_name=$(echo "Kitchen app")
	repo_url=$(echo "http://github.com/TeamKeyblade/android_manifest.git")
	setupcode
fi

if [ $setupanswer == "4" ]; then
	script_repo=$(echo "aokp")
	repo_platform=$(echo "ics")
	repo_name=$(echo "Android Open Kang Project")
	repo_url=$(echo "http://github.com/AOKP/platform_manifest.git")
	setupcode
fi

if [ $setupanswer == "5" ]; then
	script_repo=$(echo "aosp")
	repo_platform=$(echo "android-4.0.4_r2.1")
	repo_name=$(echo "Android Open Source Project")
	repo_url=$(echo "https://android.googlesource.com/platform/manifest")
	setupcode
fi

if [ $setupanswer == "6" ]; then
	script_repo=$(echo "cm")
	repo_platform=$(echo "ics")
	repo_name=$(echo "Cyanogenmod 9")
	repo_url=$(echo "http://github.com/CyanogenMod/android.git")
	setupcode
fi

if [ $setupanswer == "7" ]; then
	script_repo=$(echo "evervolv")
	repo_platform=$(echo "ics")
	repo_name=$(echo "Evervolv")
	repo_url=$(echo "http://github.com/Evervolv/android.git")
	setupcode
fi

if [ $setupanswer == "8" ]; then
	script_repo=$(echo "rooted-aosp")
	repo_platform=$(echo "ics")
	repo_name=$(echo "Rooted & Busyboxed AOSP")
	repo_url=$(echo "http://github.com/TeamKeyblade/android_manifest.git")
	setupcode
fi

if [ $setupanswer == "9" ]; then
	script_repo=$(echo "sts")
	repo_platform=$(echo "ics")
	repo_name=$(echo "Solana/Targa/Spyder Dev Team")
	repo_url=$(echo "http://github.com/CyanogenMod/android.git") # not a typo, sts doesnt have theyre own true manifest
	setupcode
fi

if [ $setupanswer == "10" ]; then
	script_repo=$(echo "gummy")
	repo_platform=$(echo "master") # its ridiculous that they use master for the ics branch on github..
	repo_name=$(echo "Team Gummy")
	repo_url=$(echo "http://github.com/teamgummy/platform_manifest.git")
	setupcode
fi

if [ $setupanswer == "11" ]; then
	echo ""
	read -p "Returning to Main Menu, Press Enter to continue: " done
	exit 0
fi

menu
}
menu
