#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	export test=$(echo "$1")
fi

if [ ! "$test" == "" ]; then
	export AUTO=true
fi

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "reposync")
	../headerfile
	exit 0
fi

menu () {
if [ ! $AUTO ]; then
	clear
fi

supersync=$( expr $THREADS_TOTAL \* 2 )

if [ ! $AUTO ]; then
	echo "Swordrune10's Android Kitchen!"
	echo "=============================="
	echo "What are we updating?"
	echo "  1. Update the Kitchen app repository"
	echo "  2. Update the Android Open Kang Project repository"
	echo "  3. Update the Android Open Source Project repository"
	echo "  4. Update the Cyanogenmod 9 repository"
	echo "  5. Update the Evervolv repository"
	echo "  6. Update the Rooted & Busyboxed AOSP repository"
	echo "  7. Update the Solana/Targa/Spyder Dev Team repository"
	echo "  8. Update the Team Gummy repository"
	echo "  9. Update all available repositories"
	echo "  10. Go Back"
	read version

	if [ "$version" == "" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
	fi

	if ( echo $version | grep -q [A-Za-z] ); then
		echo ""
		echo "You did not make a proper selection, try again!"
		echo "Press Enter to continue"
		read -p "Press Enter to continue: " done
	fi

	if [ $version -gt "10" ]; then
		echo ""
		echo "You did not make a proper selection, try again!"
		read -p "Press Enter to continue: " done
	fi
fi

if [ ! "$test" == "" ]; then
	if [ $test == "list" ]; then
		echo "kitchen = Update Kitchen"
		echo "aokp = Update Android Open Kang Project"
		echo "aosp = Update Android Open Source Project"
		echo "cm = Update Cyanogenmod 9"
		echo "ev = Update Evervolv"
		echo "raosp = Update Rooted & Busyboxed AOSP"
		echo "sts = Update Solana/Targa/Spyder Dev Team"
		echo "gummy = Update Team Gummy"
		echo "all = Update all available repos"
		exit 0
	fi

	if [ $test == "kitchen" ]; then
		version="1"
	fi

	if [ $test == "aokp" ]; then
		version="2"
	fi

	if [ $test == "aosp" ]; then
		version="3"
	fi

	if [ $test == "cm" ]; then
		version="4"
	fi

	if [ $test == "ev" ] || [ $test == "evervolv" ]; then
		version="5"
	fi

	if [ $test == "raosp" ] || [ $test == "rooted-aosp" ]; then
		version="6"
	fi

	if [ $test == "sts" ]; then
		version="7"
	fi

	if [ $test == "gummy" ]; then
		version="8"
	fi

	if [ $test == "all" ]; then
		version="9"
	fi
fi

if [ $version == "1" ] || [ $version == "9" ]; then
	echo ""
	echo "Updating the Kitchen app repository.."
	cd $LOCAL/..

	repo sync -j$THREADS_TOTAL
	echo ""
	echo "Kitchen Update Complete!"

	if [ ! $AUTO ]; then
		read -p "Press Enter to continue: " done
	fi
fi

if [ $version == "2" ]; then
	export SCRIPT_REPO=$(echo "aokp")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Android Open Kang Project")
	synccode
fi

if [ $version == "3" ]; then
	export SCRIPT_REPO=$(echo "aosp")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Android Open Source Project")
	synccode
fi

if [ $version == "4" ]; then
	export SCRIPT_REPO=$(echo "cm")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Cyanogenmod 9")
	synccode
fi


if [ $version == "5" ]; then
	export SCRIPT_REPO=$(echo "evervolv")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Evervolv")
	synccode
fi

if [ $version == "6" ]; then
	export SCRIPT_REPO=$(echo "rooted-aosp")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Rooted & Busyboxed AOSP")
	synccode
fi

if [ $version == "7" ]; then
	export SCRIPT_REPO=$(echo "sts")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Solana/Targa/Spyder Dev Team")
	synccode
fi

if [ $version == "8" ]; then
	export SCRIPT_REPO=$(echo "gummy")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Team Gummy")
	synccode
fi

if [ $version == "9" ]; then
	export SCRIPT_REPO=$(echo "aokp")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Android Open Kang Project")
	synccode
	export SCRIPT_REPO=$(echo "aosp")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Android Open Source Project")
	synccode
	export SCRIPT_REPO=$(echo "cm")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Cyanogenmod 9")
	synccode
	export SCRIPT_REPO=$(echo "evervolv")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Evervolv")
	synccode
	export SCRIPT_REPO=$(echo "rooted-aosp")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Rooted & Busyboxed AOSP")
	synccode
	export SCRIPT_REPO=$(echo "sts")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Solana/Targa/Spyder Dev Team")
	synccode
	export SCRIPT_REPO=$(echo "gummy")
	export REPO_PLATFORM=$(echo "ics")
	repo_name=$(echo "Team Gummy")
	synccode
fi

synccode() {
if ( find $DOTREPO &> /dev/null); then
	echo ""
	echo "Updating $repo_name repository.."
	cd $REPOFOLDER

	preupdate
	repo sync -j$supersync

	$LOCAL/config/gitpuller

	postupdate

	echo ""
	echo "$repo_name Update Complete!"

	if [ ! $AUTO ]; then
		read -p "Press Enter to continue: " done
	fi
else
	echo ""
	echo "$repo_name not initialized, aborting.. "

	if [ ! $AUTO ]; then
		read -p "Press Enter to continue: " done
	fi
fi
}

if [ $version == "10" ]; then
	echo ""
	read -p "Returning to Main Menu, Press Enter to continue: " done
	exit 0
fi

if [ $AUTO ]; then
	exit 0
fi

menu
}
menu
