#!/bin/bash
# Written by Sean Donovan (swordrune10)

if [ ! "$INIT" ]; then
	cd $(dirname $0)
	export SCRIPT=$(echo "reposetup")
	../headerfile
	exit 0
fi

menu () {
clear

echo "Swordrune10's Android Kitchen!"
echo "=============================="
echo "What are we setting up?"
echo "  1. Install the repo command"
echo "  2. initialize the build enviroment"
echo "  3. initialize the Kitchen app repository"
echo "  4. initialize the Android Open Kang Project repository"
echo "  5. initialize the Android Open Source Project repository"
echo "  6. initialize the Cyanogenmod 9 repository"
echo "  7. initialize the Evervolv repository"
echo "  8. initialize the Rooted & Busyboxed AOSP repository"
echo "  9. initialize the Solana/Targa/Spyder Dev Team repository"
echo "  10. initialize the Team Gummy repository"
echo "  11. Go Back"
echo ""
echo "Which one would you like to do?"
read setupanswer

if [ "$setupanswer" == "" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if ( echo $setupanswer | grep -q [A-Za-z] ); then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer -gt "11" ]; then
	echo ""
	echo "You did not make a proper selection, try again!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "1" ]; then
	if ( type -a repo &> /dev/null ); then
		echo ""
		echo "repo is already installed.."
	else
		echo ""
		echo "Installing the repo command.."

		if ( ! find ~/bin &> /dev/null ); then
			mkdir ~/bin
		fi

		wget https://dl-ssl.google.com/dl/googlesource/git-repo/repo -O ~/bin/repo
		chmod a+x ~/bin/repo

		echo ""
		echo "Finished!"
		read -p "Press Enter to continue: " done
	fi
fi

if [ $setupanswer == "2" ]; then
	environmentsetup
fi

if [ $setupanswer == "3" ]; then
	echo "initializing the Kitchen app repository.."

	cd $LOCAL/..
	repo init -u http://github.com/TeamKeyblade/android_manifest.git -b stable

	echo ""
	echo "Sync the Kitchen app repository?"
	read -p "yes/no? " kitchensync

	if [ "$kitchensync" == "yes" ] || [ "$kitchensync" == "y" ]; then
		reposync kitchen
	fi

	if [ "$kitchensync" == "" ] || [ "$kitchensync" == "no" ] || [ "$kitchensync" == "n" ]; then
		echo ""
		echo "Kitchen app repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "4" ]; then
	echo "initializing the Android Open Kang Project repository.."

	mkdir -p $REPOS/aokp-ics
	cd $REPOS/aokp-ics
	repo init -u git://github.com/AOKP/platform_manifest.git -b ics

	echo ""
	echo "Sync the Android Open Kang Project repository?"
	read -p "yes/no? " aokpsync

	if [ "$aokpsync" == "yes" ] || [ "$aokpsync" == "y" ]; then
		reposync aokp
	fi

	if [ "$aokpsync" == "" ] || [ "$aokpsync" == "no" ] || [ "$aokpsync" == "n" ]; then
		echo ""
		echo "Android Open Kang Project repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "5" ]; then
	echo "initializing the Android Open Source Project repository.."

	mkdir -p $REPOS/aosp-ics
	cd $REPOS/aosp-ics
	repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.4_r2.1

	echo ""
	echo "Sync the Android Open Source Project repository?"
	read -p "yes/no? " aospsync

	if [ "$aospsync" == "yes" ] || [ "$aospsync" == "y" ]; then
		reposync aosp
	fi

	if [ "$aospsync" == "" ] || [ "$aospsync" == "no" ] || [ "$aospsync" == "n" ]; then
		echo ""
		echo "Android Open Source Project repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "6" ]; then
	echo "initializing the Cyanogenmod 9 repository.."

	mkdir -p $REPOS/cm-ics
	cd $REPOS/cm-ics
	repo init -u http://github.com/CyanogenMod/android.git -b ics

	echo ""
	echo "Sync the Cyanogenmod 9 repository?"
	read -p "yes/no? " cm9sync

	if [ "$cm9sync" == "yes" ] || [ "$cm9sync" == "y" ]; then
		reposync cm
	fi

	if [ "$cm9sync" == "" ] || [ "$cm9sync" == "no" ] || [ "$cm9sync" == "n" ]; then
		echo ""
		echo "Cyanogenmod 9 repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "7" ]; then
	echo "initializing the Evervolv repository.."

	mkdir -p $REPOS/evervolv-ics
	cd $REPOS/evervolv-ics
	repo init -u git://github.com/Evervolv/android.git -b ics

	echo ""
	echo "Sync the Android Open Source Project repository?"
	read -p "yes/no? " evervolvsync

	if [ "$evervolvsync" == "yes" ] || [ "$evervolvsync" == "y" ]; then
		reposync ev
	fi

	if [ "$evervolvsync" == "" ] || [ "$evervolvsync" == "no" ] || [ "$evervolvsync" == "n" ]; then
		echo ""
		echo "Evervolv repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "8" ]; then
	echo "initializing the Rooted & Busyboxed AOSP repository.."

	mkdir -p $REPOS/rooted-aosp-ics
	cd $REPOS/rooted-aosp-ics
	repo init -u http://github.com/TeamKeyblade/android_manifest.git -b ics

	echo ""
	echo "Sync the Rooted & Busyboxed AOSP repository?"
	read -p "yes/no? " raospsync

	if [ "$raospsync" == "yes" ] || [ "$raospsync" == "y" ]; then
		reposync raosp
	fi

	if [ "$raospsync" == "" ] || [ "$raospsync" == "no" ] || [ "$raospsync" == "n" ]; then
		echo ""
		echo "Rooted & Busyboxed AOSP repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "9" ]; then
	echo "initializing the Solana/Targa/Spyder Dev Team repository.."

	mkdir -p $REPOS/sts-ics
	cd $REPOS/sts-ics
	repo init -u git://github.com/CyanogenMod/android.git -b ics

	wget https://raw.github.com/STS-Dev-Team/android_local_STS/ics/local_manifest.xml -O ./local_manifest.xml

	echo ""
	echo "Sync the Solana/Targa/Spyder repository?"
	read -p "yes/no? " stssync

	if [ "$stssync" == "yes" ] || [ "$stssync" == "y" ]; then
		reposync sts
	fi

	if [ "$stssync" == "" ] || [ "$stssync" == "no" ] || [ "$stssync" == "n" ]; then
		echo ""
		echo "Solana/Targa/Spyder Dev Team repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "10" ]; then
	echo "initializing the Team Gummy repository.."

	mkdir -p $REPOS/gummy-ics
	cd $REPOS/gummy-ics
	repo init -u https://github.com/teamgummy/platform_manifest.git -b master

	echo ""
	echo "Sync the Team Gummy repository?"
	read -p "yes/no? " gummysync

	if [ "$gummysync" == "yes" ] || [ "$gummysync" == "y" ]; then
		reposync gummy
	fi

	if [ "$gummysync" == "" ] || [ "$gummysync" == "no" ] || [ "$gummysync" == "n" ]; then
		echo ""
		echo "Team Gummy repository did not sync.."
	fi

	echo ""
	echo "Finished!"
	read -p "Press Enter to continue: " done
fi

if [ $setupanswer == "11" ]; then
	echo ""
	read -p "Returning to Main Menu, Press Enter to continue: " done
	exit 0
fi

menu
}
menu
